#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattleItemHandle_WeapAttachmentPC

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Basic_structs.hpp"
#include "ShadowTrackerExtra_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BattleItemHandle_WeapAttachmentPC.BattleItemHandle_WeapAttachmentPC_C
// 0x0030 (0x0270 - 0x0240)
class UBattleItemHandle_WeapAttachmentPC_C final : public UBackpackWeaponAttachHandle
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0240(0x0008)(Transient, DuplicateTransient)
	class ASTExtraShootWeapon*                    Weapon;                                            // 0x0248(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 WrapperClass;                                      // 0x0250(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBackpackComponent*                     OwningBackpackComponent;                           // 0x0258(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASTExtraBaseCharacter*                  OwningCharacter;                                   // 0x0260(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBattleItemHandle_MainWeaponPC_C*       CachedWeaponHandle;                                // 0x0268(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BattleItemHandle_WeapAttachmentPC(int32 EntryPoint);
	void ReturnWeaponAdditionalBulletsToBackpack(class ASTExtraShootWeapon* Weapon_0, int32 BulletNum);
	uint8 HandleUse(const struct FBattleItemUseTarget& Target, EBattleItemUseReason Reason);
	uint8 HandleDisuse(EBattleItemDisuseReason Reason);
	uint8 HandlePickup(TScriptInterface<class IItemContainerInterface>& ItemContainer, const struct FBattleItemPickupInfo& PickupInfo, EBattleItemPickupReason Reason);
	uint8 HandleDrop(int32 InCount, EBattleItemDropReason Reason);
	void CreateWrapperOnGround(int32 Count_0);
	void FilterWeaponItemHandle(class UBattleItemHandleBase_BP_C* InputItemHandle, uint8 IsPickupDirectlyEquip, const struct FBattleItemPickupInfo& PickupInfo, struct FBattleItemUseTarget* Target, uint8* HasTarget, class UBattleItemHandle_MainWeaponPC_C** TargetWeaponHandle, class ASTExtraWeapon** WeaponActor);
	void CanSwap(class UBackpackWeaponAttachHandle* SpecificID, uint8* Can);
	void CurBackpackCapacity(class UBattleItemHandle_WeapAttachmentPC_C* ItemHandle, uint8* IsDrop);

	class UWorld* GetWorldInternal() const;
	struct FBattleItemData ExtractItemData() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BattleItemHandle_WeapAttachmentPC_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BattleItemHandle_WeapAttachmentPC_C")
	}
	static class UBattleItemHandle_WeapAttachmentPC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBattleItemHandle_WeapAttachmentPC_C>();
	}
};

}

