#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattleItemHandleBase_BP

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Basic_structs.hpp"
#include "Basic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BattleItemHandleBase_BP.BattleItemHandleBase_BP_C
// 0x0088 (0x0150 - 0x00C8)
#pragma pack(push, 0x1)
class alignas(0x10) UBattleItemHandleBase_BP_C : public UBattleItemHandleBase
{
public:
	class ASTExtraPlayerController*               OwningPlayerController;                            // 0x00C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASTExtraBaseCharacter*                  OwningCharacter;                                   // 0x00D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBackpackComponent*                     OwningBackpackComponent;                           // 0x00D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             WrapperPutdownTrans;                               // 0x00E0(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FTransform                             SourceWrapperTrans;                                // 0x0110(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	class ABaseAIController*                      OwningAIController;                                // 0x0140(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	uint8 HandlePickup(TScriptInterface<class IItemContainerInterface>& ItemContainer, const struct FBattleItemPickupInfo& PickupInfo, EBattleItemPickupReason Reason);
	uint8 HandleDrop(int32 InCount, EBattleItemDropReason Reason);
	uint8 HandleUse(const struct FBattleItemUseTarget& Target, EBattleItemUseReason Reason);
	uint8 HandleDisuse(EBattleItemDisuseReason Reason);
	void SpawnWrapperOnGround(class UClass* WrapperClass, uint8 bUseRandomLoc, class APickUpWrapperActor** TargetWrapper);

	struct FBattleItemData ExtractItemData() const;
	class UWorld* GetWorldInternal() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BattleItemHandleBase_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BattleItemHandleBase_BP_C")
	}
	static class UBattleItemHandleBase_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBattleItemHandleBase_BP_C>();
	}
};
#pragma pack(pop)

}

