#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AirDropBox

#include "Basic.hpp"

#include "BP_AirDropBox_classes.hpp"
#include "BP_AirDropBox_parameters.hpp"


namespace SDK
{

// Function BP_AirDropBox.BP_AirDropBox_C.ExecuteUbergraph_BP_AirDropBox
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AirDropBox_C::ExecuteUbergraph_BP_AirDropBox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "ExecuteUbergraph_BP_AirDropBox");

	Params::BP_AirDropBox_C_ExecuteUbergraph_BP_AirDropBox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AirDropBox.BP_AirDropBox_C.ChangeAirdropAppearance
// (Event, Public, BlueprintEvent)

void ABP_AirDropBox_C::ChangeAirdropAppearance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "ChangeAirdropAppearance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AirDropBox.BP_AirDropBox_C.BndEvt__Box1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_AirDropBox_C::BndEvt__Box1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, uint8 bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "BndEvt__Box1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_AirDropBox_C_BndEvt__Box1_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AirDropBox.BP_AirDropBox_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AirDropBox_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "ReceiveTick");

	Params::BP_AirDropBox_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AirDropBox.BP_AirDropBox_C.DistanceScalerChangedEvent
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   Scale                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AirDropBox_C::DistanceScalerChangedEvent(float Scale)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "DistanceScalerChangedEvent");

	Params::BP_AirDropBox_C_DistanceScalerChangedEvent Parms{};

	Parms.Scale = Scale;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AirDropBox.BP_AirDropBox_C.BndEvt__Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_AirDropBox_C::BndEvt__Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, uint8 bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "BndEvt__Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_AirDropBox_C_BndEvt__Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AirDropBox.BP_AirDropBox_C.OnLandBroadCast
// (BlueprintCallable, BlueprintEvent)

void ABP_AirDropBox_C::OnLandBroadCast()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "OnLandBroadCast");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AirDropBox.BP_AirDropBox_C.HideSmoke
// (BlueprintCallable, BlueprintEvent)

void ABP_AirDropBox_C::HideSmoke()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "HideSmoke");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AirDropBox.BP_AirDropBox_C.BndEvt__Cube_K2Node_ComponentBoundEvent_2_ComponentHitSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_AirDropBox_C::BndEvt__Cube_K2Node_ComponentBoundEvent_2_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "BndEvt__Cube_K2Node_ComponentBoundEvent_2_ComponentHitSignature__DelegateSignature");

	Params::BP_AirDropBox_C_BndEvt__Cube_K2Node_ComponentBoundEvent_2_ComponentHitSignature__DelegateSignature Parms{};

	Parms.HitComponent = HitComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AirDropBox.BP_AirDropBox_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_AirDropBox_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AirDropBox.BP_AirDropBox_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_AirDropBox_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AirDropBox.BP_AirDropBox_C.CheckBoxIsLand
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_AirDropBox_C::CheckBoxIsLand()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "CheckBoxIsLand");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AirDropBox.BP_AirDropBox_C.GetRandomGenerateWrappersData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FAirDropBoxGenerateWrapperItemData>*GenerateData                                           (Parm, OutParm, ZeroConstructor)

void ABP_AirDropBox_C::GetRandomGenerateWrappersData(TArray<struct FAirDropBoxGenerateWrapperItemData>* GenerateData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "GetRandomGenerateWrappersData");

	Params::BP_AirDropBox_C_GetRandomGenerateWrappersData Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (GenerateData != nullptr)
		*GenerateData = std::move(Parms.GenerateData);
}


// Function BP_AirDropBox.BP_AirDropBox_C.OnRep_bIsBoxHitTheGroundOrInWater
// (BlueprintCallable, BlueprintEvent)

void ABP_AirDropBox_C::OnRep_bIsBoxHitTheGroundOrInWater()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "OnRep_bIsBoxHitTheGroundOrInWater");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AirDropBox.BP_AirDropBox_C.OnRep_bIsParachuteOpen
// (BlueprintCallable, BlueprintEvent)

void ABP_AirDropBox_C::OnRep_bIsParachuteOpen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "OnRep_bIsParachuteOpen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AirDropBox.BP_AirDropBox_C.OnRep_bIsBoxSomking
// (BlueprintCallable, BlueprintEvent)

void ABP_AirDropBox_C::OnRep_bIsBoxSomking()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "OnRep_bIsBoxSomking");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AirDropBox.BP_AirDropBox_C.OnRep_bIsBoxInWater
// (BlueprintCallable, BlueprintEvent)

void ABP_AirDropBox_C::OnRep_bIsBoxInWater()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "OnRep_bIsBoxInWater");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AirDropBox.BP_AirDropBox_C.OnRep_ServerDroppingSpeed
// (HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_AirDropBox_C::OnRep_ServerDroppingSpeed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "OnRep_ServerDroppingSpeed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AirDropBox.BP_AirDropBox_C.IsWater
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class AActor*                           NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8*                                  IsWater_0                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_AirDropBox_C::IsWater(class AActor* NewParam, uint8* IsWater_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "IsWater");

	Params::BP_AirDropBox_C_IsWater Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);

	if (IsWater_0 != nullptr)
		*IsWater_0 = Parms.IsWater_0;
}


// Function BP_AirDropBox.BP_AirDropBox_C.GetSuperAirDropGenerateWrappersData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FAirDropBoxGenerateWrapperItemData>*RetData                                                (Parm, OutParm, ZeroConstructor)

void ABP_AirDropBox_C::GetSuperAirDropGenerateWrappersData(TArray<struct FAirDropBoxGenerateWrapperItemData>* RetData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "GetSuperAirDropGenerateWrappersData");

	Params::BP_AirDropBox_C_GetSuperAirDropGenerateWrappersData Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (RetData != nullptr)
		*RetData = std::move(Parms.RetData);
}


// Function BP_AirDropBox.BP_AirDropBox_C.OnComponentHit_Box
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_AirDropBox_C::OnComponentHit_Box()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "OnComponentHit_Box");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AirDropBox.BP_AirDropBox_C.GenerateItemBox
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_AirDropBox_C::GenerateItemBox()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_AirDropBox_C", "GenerateItemBox");

	UObject::ProcessEvent(Func, nullptr);
}

}

