#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bp_complaint

#include "Basic.hpp"

#include "bp_complaint_classes.hpp"


namespace SDK
{

// Function bp_complaint.bp_complaint_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventComplaintGetTeamlist
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventComplaintGetTeamlist()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventComplaintGetTeamlist");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventComplaintGetTeamlist_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventComplaintGetTeamlist_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventComplaintGetTeamlist_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventComplaintNumEmptyTips
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventComplaintNumEmptyTips()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventComplaintNumEmptyTips");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventComplaintNumEmptyTips_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventComplaintNumEmptyTips_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventComplaintNumEmptyTips_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventComplaintRefreshUI
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventComplaintRefreshUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventComplaintRefreshUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventComplaintRefreshUI_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventComplaintRefreshUI_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventComplaintRefreshUI_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventNameHadComplaintedTips
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventNameHadComplaintedTips()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventNameHadComplaintedTips");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventNameHadComplaintedTips_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventNameHadComplaintedTips_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventNameHadComplaintedTips_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventComplaintClickSubmit
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventComplaintClickSubmit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventComplaintClickSubmit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventComplaintClickSubmit_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventComplaintClickSubmit_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventComplaintClickSubmit_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventComplaintClickReplay
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventComplaintClickReplay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventComplaintClickReplay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventComplaintClickReplay_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventComplaintClickReplay_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventComplaintClickReplay_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventComplaintClose
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventComplaintClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventComplaintClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventComplaintClose_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventComplaintClose_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventComplaintClose_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventComplaintNumOverTips
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventComplaintNumOverTips()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventComplaintNumOverTips");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_complaint.bp_complaint_C.EventComplaintNumOverTips_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_complaint_C::EventComplaintNumOverTips_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_complaint_C", "EventComplaintNumOverTips_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}

}

