#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bp_common_treasurebox_popup

#include "Basic.hpp"

#include "bp_common_treasurebox_popup_classes.hpp"


namespace SDK
{

// Function bp_common_treasurebox_popup.bp_common_treasurebox_popup_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void Abp_common_treasurebox_popup_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_common_treasurebox_popup_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_common_treasurebox_popup.bp_common_treasurebox_popup_C.EventCommonTreasureBoxPopupClosePanel
// (BlueprintCallable, BlueprintEvent)

void Abp_common_treasurebox_popup_C::EventCommonTreasureBoxPopupClosePanel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_common_treasurebox_popup_C", "EventCommonTreasureBoxPopupClosePanel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_common_treasurebox_popup.bp_common_treasurebox_popup_C.EventCommonTreasureBoxPopupClosePanel_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_common_treasurebox_popup_C::EventCommonTreasureBoxPopupClosePanel_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_common_treasurebox_popup_C", "EventCommonTreasureBoxPopupClosePanel_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}

}

