#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bp_common_helptips_panel

#include "Basic.hpp"

#include "BP_STRUCT_GlobalHelpTips_Pos_structs.hpp"
#include "Client_classes.hpp"


namespace SDK
{

// ScriptBlueprintGeneratedClass bp_common_helptips_panel.bp_common_helptips_panel_C
// 0x0030 (0x0418 - 0x03E8)
class Abp_common_helptips_panel_C final : public ALuaClassObj
{
public:
	class UScriptContextComponent*                Generated_ScriptContext;                           // 0x03E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	int32                                         BP_CommonHelpTips_StringID;                        // 0x03F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBP_STRUCT_GlobalHelpTips_Pos          BP_STRUCT_GlobalHelpTips_Pos;                      // 0x03F4(0x0008)(Edit, BlueprintVisible, HasGetValueTypeHash)
	uint8                                         Pad_3FC[0x4];                                      // 0x03FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 BP_CommonHelpTips_String;                          // 0x0400(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0410(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("bp_common_helptips_panel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"bp_common_helptips_panel_C")
	}
	static class Abp_common_helptips_panel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Abp_common_helptips_panel_C>();
	}
};

}

