#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bp_chat_entrance

#include "Basic.hpp"

#include "bp_chat_entrance_classes.hpp"


namespace SDK
{

// Function bp_chat_entrance.bp_chat_entrance_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventClickBtnRecruit
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventClickBtnRecruit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventClickBtnRecruit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventClickBtnRecruit_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventClickBtnRecruit_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventClickBtnRecruit_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventAchieveQuickMsgStr
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventAchieveQuickMsgStr()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventAchieveQuickMsgStr");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventAchieveQuickMsgStr_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventAchieveQuickMsgStr_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventAchieveQuickMsgStr_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventTestJoinGameRoom
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventTestJoinGameRoom()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventTestJoinGameRoom");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventTestJoinGameRoom_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventTestJoinGameRoom_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventTestJoinGameRoom_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventPopMessageBuffer
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventPopMessageBuffer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventPopMessageBuffer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventPopMessageBuffer_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventPopMessageBuffer_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventPopMessageBuffer_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventOpenChatWindow
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventOpenChatWindow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventOpenChatWindow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventOpenChatWindow_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventOpenChatWindow_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventOpenChatWindow_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventTestQuitRoom
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventTestQuitRoom()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventTestQuitRoom");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventTestQuitRoom_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventTestQuitRoom_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventTestQuitRoom_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventFetchInfo
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventFetchInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventFetchInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventFetchInfo_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventFetchInfo_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventFetchInfo_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventOpenFriendNewChat
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventOpenFriendNewChat()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventOpenFriendNewChat");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventOpenFriendNewChat_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventOpenFriendNewChat_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventOpenFriendNewChat_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventSendTeamQuickMsg
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventSendTeamQuickMsg()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventSendTeamQuickMsg");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventSendTeamQuickMsg_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventSendTeamQuickMsg_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventSendTeamQuickMsg_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventSetInfo_Push
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventSetInfo_Push()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventSetInfo_Push");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventSetInfo_Push_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventSetInfo_Push_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventSetInfo_Push_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventOpenChatUI
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventOpenChatUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventOpenChatUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function bp_chat_entrance.bp_chat_entrance_C.EventOpenChatUI_NoFetch
// (BlueprintCallable, BlueprintEvent)

void Abp_chat_entrance_C::EventOpenChatUI_NoFetch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("bp_chat_entrance_C", "EventOpenChatUI_NoFetch");

	UObject::ProcessEvent(Func, nullptr);
}

}

