#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bp_chat_entrance

#include "Basic.hpp"

#include "Client_classes.hpp"


namespace SDK
{

// ScriptBlueprintGeneratedClass bp_chat_entrance.bp_chat_entrance_C
// 0x0088 (0x0460 - 0x03D8)
class Abp_chat_entrance_C final : public ALuaClassObj
{
public:
	class UScriptContextComponent*                Generated_ScriptContext;                           // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	int32                                         BP_ChatEntranceChatroomNewMsgCount;                // 0x03E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         BP_ChatEntranceTeamed : 1;                         // 0x03E4(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_3E5[0x3];                                      // 0x03E5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 BP_ChatEntranceNewSender;                          // 0x03E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 BP_ChatEntranceNewMsg;                             // 0x03F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         BP_ChatFriendNewMsgCount;                          // 0x0408(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_40C[0x4];                                      // 0x040C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 BP_ChatEntranceVoiceRoomId;                        // 0x0410(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	uint8                                         BP_ChatEntranceEnterRoom : 1;                      // 0x0420(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         BP_ChatEntranceTickBufferList : 1;                 // 0x0421(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_422[0x6];                                      // 0x0422(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 BP_ChatEntranceClearGID;                           // 0x0428(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         BP_ChatEntranceNewChannel;                         // 0x0438(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BP_ChatEntranceQuickMsgId;                         // 0x043C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 BP_ChatEntranceQuickMsgStr;                        // 0x0440(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	uint8                                         BP_ChatEntranceEnterCorps : 1;                     // 0x0450(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         BP_ChatEntranceValid : 1;                          // 0x0451(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_452[0x6];                                      // 0x0452(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void EventClickBtnRecruit();
	void EventClickBtnRecruit_NoFetch();
	void EventSendTeamQuickMsg();
	void EventSendTeamQuickMsg_NoFetch();
	void EventPopMessageBuffer();
	void EventPopMessageBuffer_NoFetch();
	void EventSetInfo_Push();
	void EventSetInfo_Push_NoFetch();
	void EventOpenFriendNewChat();
	void EventOpenFriendNewChat_NoFetch();
	void EventOpenChatWindow();
	void EventOpenChatWindow_NoFetch();
	void EventOpenChatUI();
	void EventOpenChatUI_NoFetch();
	void EventTestJoinGameRoom();
	void EventTestJoinGameRoom_NoFetch();
	void EventAchieveQuickMsgStr();
	void EventAchieveQuickMsgStr_NoFetch();
	void EventTestQuitRoom();
	void EventTestQuitRoom_NoFetch();
	void EventFetchInfo();
	void EventFetchInfo_NoFetch();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("bp_chat_entrance_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"bp_chat_entrance_C")
	}
	static class Abp_chat_entrance_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Abp_chat_entrance_C>();
	}
};

}

