#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bp_corps_rank

#include "Basic.hpp"

#include "BP_STRUCT_CorpsUinInfo_structs.hpp"
#include "BP_STRUCT_CorpsRankInfo_structs.hpp"
#include "BP_STRUCT_MyCorpsRankInfo_structs.hpp"
#include "Client_classes.hpp"


namespace SDK
{

// ScriptBlueprintGeneratedClass bp_corps_rank.bp_corps_rank_C
// 0x00C0 (0x0498 - 0x03D8)
class Abp_corps_rank_C final : public ALuaClassObj
{
public:
	class UScriptContextComponent*                Generated_ScriptContext;                           // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	TArray<struct FBP_STRUCT_CorpsUinInfo>        BP_ARRAY_Corps_RankUinList;                        // 0x03E0(0x0010)(Edit, BlueprintVisible, ZeroConstructor)
	int32                                         BP_STRUCT_MyCorpsRankNum;                          // 0x03F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3F4[0x4];                                      // 0x03F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBP_STRUCT_CorpsRankInfo               BP_STRUCT_CorpsRankInfo;                           // 0x03F8(0x0038)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FBP_STRUCT_MyCorpsRankInfo             BP_STRUCT_MyCorpsRankInfo;                         // 0x0430(0x0038)(Edit, BlueprintVisible, HasGetValueTypeHash)
	int32                                         BP_STRUCT_MyCorpsRankNumPro;                       // 0x0468(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BP_Corps_Rank_Trans_Begin_Index;                   // 0x046C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FBP_STRUCT_CorpsRankInfo>       BP_ARRAY_Corps_RankInfoList;                       // 0x0470(0x0010)(Edit, BlueprintVisible, ZeroConstructor)
	int32                                         BP_Corps_Rank_Current_ID;                          // 0x0480(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BP_Crops_Rank_Now_Type;                            // 0x0484(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBP_STRUCT_CorpsUinInfo                BP_STRUCT_CorpsUinInfo;                            // 0x0488(0x0004)(Edit, BlueprintVisible, HasGetValueTypeHash)
	int32                                         BP_Corps_Rank_Trans_End_Index;                     // 0x048C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void EventCorpsRankTypeChange();
	void EventCorpsRankTypeChange_NoFetch();
	void EventCorpsRankShowCorpsDetails();
	void EventCorpsRankShowCorpsDetails_NoFetch();
	void EventCorpsRankShowUI();
	void EventCorpsRankShowUI_NoFetch();
	void EventCorpsRankHideUI();
	void EventCorpsRankHideUI_NoFetch();
	void EventCorpsRankGetNextInfo();
	void EventCorpsRankGetNextInfo_NoFetch();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("bp_corps_rank_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"bp_corps_rank_C")
	}
	static class Abp_corps_rank_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Abp_corps_rank_C>();
	}
};

}

