#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DJ_Large_EQ_Pickup

#include "Basic.hpp"

#include "BP_DJ_Large_EQ_Pickup_classes.hpp"


namespace SDK
{

// Function BP_DJ_Large_EQ_Pickup.BP_DJ_Large_EQ_Pickup_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_DJ_Large_EQ_Pickup_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_DJ_Large_EQ_Pickup_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

