#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bp_festival_share_award

#include "Basic.hpp"

#include "BP_STRUCT_FestivalShareActInfo_structs.hpp"
#include "Client_classes.hpp"


namespace SDK
{

// ScriptBlueprintGeneratedClass bp_festival_share_award.bp_festival_share_award_C
// 0x0078 (0x0460 - 0x03E8)
class Abp_festival_share_award_C final : public ALuaClassObj
{
public:
	class UScriptContextComponent*                Generated_ScriptContext;                           // 0x03E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	class FString                                 BP_FestivalShare_ActiveTime;                       // 0x03F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	uint8                                         BP_FestivalShare_IsTodayDone : 1;                  // 0x0400(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_401[0x3];                                      // 0x0401(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         BP_FestivalShare_CurNum;                           // 0x0404(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBP_STRUCT_FestivalShareActInfo        BP_STRUCT_FestivalShareActInfo;                    // 0x0408(0x0038)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<struct FBP_STRUCT_FestivalShareActInfo> BP_ARRAY_FestivalShareActInfoList;                // 0x0440(0x0010)(Edit, BlueprintVisible, ZeroConstructor)
	int32                                         BP_FestivalShare_GetAwardIndex;                    // 0x0450(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_454[0x4];                                      // 0x0454(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void EventFestivalShareActAwardReq();
	void EventFestivalShareActAwardReq_NoFetch();
	void EventFestivalShareActBtnShare();
	void EventFestivalShareActBtnShare_NoFetch();
	void EventFestivalShareActUIHide();
	void EventFestivalShareActUIHide_NoFetch();
	void EventFestivalShareActUpdateUI();
	void EventFestivalShareActUpdateUI_NoFetch();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("bp_festival_share_award_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"bp_festival_share_award_C")
	}
	static class Abp_festival_share_award_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Abp_festival_share_award_C>();
	}
};

}

