#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_KeyboardAndMouseHintWidget

#include "Basic.hpp"

#include "BP_KeyboardAndMouseHintWidget_classes.hpp"
#include "BP_KeyboardAndMouseHintWidget_parameters.hpp"


namespace SDK
{

// Function BP_KeyboardAndMouseHintWidget.BP_KeyboardAndMouseHintWidget_C.ExecuteUbergraph_BP_KeyboardAndMouseHintWidget
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_KeyboardAndMouseHintWidget_C::ExecuteUbergraph_BP_KeyboardAndMouseHintWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_KeyboardAndMouseHintWidget_C", "ExecuteUbergraph_BP_KeyboardAndMouseHintWidget");

	Params::BP_KeyboardAndMouseHintWidget_C_ExecuteUbergraph_BP_KeyboardAndMouseHintWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_KeyboardAndMouseHintWidget.BP_KeyboardAndMouseHintWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_KeyboardAndMouseHintWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_KeyboardAndMouseHintWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_KeyboardAndMouseHintWidget.BP_KeyboardAndMouseHintWidget_C.On_KeyboardAndMouseHintSizeBox_Prepass_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          BoundWidget                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_KeyboardAndMouseHintWidget_C::On_KeyboardAndMouseHintSizeBox_Prepass_0(class UWidget* BoundWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_KeyboardAndMouseHintWidget_C", "On_KeyboardAndMouseHintSizeBox_Prepass_0");

	Params::BP_KeyboardAndMouseHintWidget_C_On_KeyboardAndMouseHintSizeBox_Prepass_0 Parms{};

	Parms.BoundWidget = BoundWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_KeyboardAndMouseHintWidget.BP_KeyboardAndMouseHintWidget_C.SetPosition
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   IsExtendMinimap                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_KeyboardAndMouseHintWidget_C::SetPosition(uint8 IsExtendMinimap)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_KeyboardAndMouseHintWidget_C", "SetPosition");

	Params::BP_KeyboardAndMouseHintWidget_C_SetPosition Parms{};

	Parms.IsExtendMinimap = IsExtendMinimap;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_KeyboardAndMouseHintWidget.BP_KeyboardAndMouseHintWidget_C.ShowHideKeyHintWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   inventoryOpened                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_KeyboardAndMouseHintWidget_C::ShowHideKeyHintWidget(uint8 inventoryOpened)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_KeyboardAndMouseHintWidget_C", "ShowHideKeyHintWidget");

	Params::BP_KeyboardAndMouseHintWidget_C_ShowHideKeyHintWidget Parms{};

	Parms.inventoryOpened = inventoryOpened;

	UObject::ProcessEvent(Func, &Parms);
}

}

