#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bp_login

#include "Basic.hpp"

#include "BP_STRUCT_ServerInfo_structs.hpp"
#include "Client_classes.hpp"


namespace SDK
{

// ScriptBlueprintGeneratedClass bp_login.bp_login_C
// 0x0068 (0x0450 - 0x03E8)
class Abp_login_C final : public ALuaClassObj
{
public:
	class UScriptContextComponent*                Generated_ScriptContext;                           // 0x03E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	struct FBP_STRUCT_ServerInfo                  BP_STRUCT_ServerInfo;                              // 0x03F0(0x0030)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<struct FBP_STRUCT_ServerInfo>          BP_ARRAY_ServerList_Info;                          // 0x0420(0x0010)(Edit, BlueprintVisible, ZeroConstructor)
	int32                                         BP_SelectedShowServerInfo;                         // 0x0430(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_434[0x4];                                      // 0x0434(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 BP_InputOpenId;                                    // 0x0438(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0448(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void EventOpenExampleUI();
	void EventOpenExampleUI_NoFetch();
	void EventLogout();
	void EventLogout_NoFetch();
	void EventShowCurrentSelect();
	void EventShowCurrentSelect_NoFetch();
	void EventHideScrollView();
	void EventHideScrollView_NoFetch();
	void EventShowScrollView();
	void EventShowScrollView_NoFetch();
	void EventConnectToGate();
	void EventConnectToGate_NoFetch();
	void EventFetchInfo();
	void EventFetchInfo_NoFetch();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("bp_login_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"bp_login_C")
	}
	static class Abp_login_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Abp_login_C>();
	}
};

}

