#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Motorbike_SideCart

#include "Basic.hpp"

#include "BP_Motorbike_SideCart_classes.hpp"
#include "BP_Motorbike_SideCart_parameters.hpp"


namespace SDK
{

// Function BP_Motorbike_SideCart.BP_Motorbike_SideCart_C.ExecuteUbergraph_BP_Motorbike_SideCart
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Motorbike_SideCart_C::ExecuteUbergraph_BP_Motorbike_SideCart(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_Motorbike_SideCart_C", "ExecuteUbergraph_BP_Motorbike_SideCart");

	Params::BP_Motorbike_SideCart_C_ExecuteUbergraph_BP_Motorbike_SideCart Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Motorbike_SideCart.BP_Motorbike_SideCart_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Motorbike_SideCart_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_Motorbike_SideCart_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Motorbike_SideCart.BP_Motorbike_SideCart_C.OnBoostingChanged
// (Event, Public, BlueprintEvent)

void ABP_Motorbike_SideCart_C::OnBoostingChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_Motorbike_SideCart_C", "OnBoostingChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Motorbike_SideCart.BP_Motorbike_SideCart_C.BndEvt__VehicleSeats_K2Node_ComponentBoundEvent_0_SeatAttachDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class ASTExtraPlayerCharacter*          Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ESTExtraVehicleSeatType                 SeatType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SeatIdx                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Motorbike_SideCart_C::BndEvt__VehicleSeats_K2Node_ComponentBoundEvent_0_SeatAttachDelegate__DelegateSignature(class ASTExtraPlayerCharacter* Character, ESTExtraVehicleSeatType SeatType, int32 SeatIdx)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_Motorbike_SideCart_C", "BndEvt__VehicleSeats_K2Node_ComponentBoundEvent_0_SeatAttachDelegate__DelegateSignature");

	Params::BP_Motorbike_SideCart_C_BndEvt__VehicleSeats_K2Node_ComponentBoundEvent_0_SeatAttachDelegate__DelegateSignature Parms{};

	Parms.Character = Character;
	Parms.SeatType = SeatType;
	Parms.SeatIdx = SeatIdx;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Motorbike_SideCart.BP_Motorbike_SideCart_C.InpActEvt_VehicleBoost_K2Node_InputActionEvent_6
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_Motorbike_SideCart_C::InpActEvt_VehicleBoost_K2Node_InputActionEvent_6(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_Motorbike_SideCart_C", "InpActEvt_VehicleBoost_K2Node_InputActionEvent_6");

	Params::BP_Motorbike_SideCart_C_InpActEvt_VehicleBoost_K2Node_InputActionEvent_6 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Motorbike_SideCart.BP_Motorbike_SideCart_C.InpActEvt_VehicleBoost_K2Node_InputActionEvent_7
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_Motorbike_SideCart_C::InpActEvt_VehicleBoost_K2Node_InputActionEvent_7(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_Motorbike_SideCart_C", "InpActEvt_VehicleBoost_K2Node_InputActionEvent_7");

	Params::BP_Motorbike_SideCart_C_InpActEvt_VehicleBoost_K2Node_InputActionEvent_7 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Motorbike_SideCart.BP_Motorbike_SideCart_C.InpActEvt_Handbrake_K2Node_InputActionEvent_8
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_Motorbike_SideCart_C::InpActEvt_Handbrake_K2Node_InputActionEvent_8(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_Motorbike_SideCart_C", "InpActEvt_Handbrake_K2Node_InputActionEvent_8");

	Params::BP_Motorbike_SideCart_C_InpActEvt_Handbrake_K2Node_InputActionEvent_8 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Motorbike_SideCart.BP_Motorbike_SideCart_C.InpActEvt_Handbrake_K2Node_InputActionEvent_9
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_Motorbike_SideCart_C::InpActEvt_Handbrake_K2Node_InputActionEvent_9(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_Motorbike_SideCart_C", "InpActEvt_Handbrake_K2Node_InputActionEvent_9");

	Params::BP_Motorbike_SideCart_C_InpActEvt_Handbrake_K2Node_InputActionEvent_9 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Motorbike_SideCart.BP_Motorbike_SideCart_C.InpActEvt_Horn_K2Node_InputActionEvent_10
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_Motorbike_SideCart_C::InpActEvt_Horn_K2Node_InputActionEvent_10(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_Motorbike_SideCart_C", "InpActEvt_Horn_K2Node_InputActionEvent_10");

	Params::BP_Motorbike_SideCart_C_InpActEvt_Horn_K2Node_InputActionEvent_10 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Motorbike_SideCart.BP_Motorbike_SideCart_C.InpActEvt_Horn_K2Node_InputActionEvent_11
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_Motorbike_SideCart_C::InpActEvt_Horn_K2Node_InputActionEvent_11(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_Motorbike_SideCart_C", "InpActEvt_Horn_K2Node_InputActionEvent_11");

	Params::BP_Motorbike_SideCart_C_InpActEvt_Horn_K2Node_InputActionEvent_11 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Motorbike_SideCart.BP_Motorbike_SideCart_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Motorbike_SideCart_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_Motorbike_SideCart_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Motorbike_SideCart.BP_Motorbike_SideCart_C.OnClientVehicleHealthStateChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ESTExtraVehicleHealthState              VehicleHealthState_0                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Motorbike_SideCart_C::OnClientVehicleHealthStateChanged(ESTExtraVehicleHealthState VehicleHealthState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_Motorbike_SideCart_C", "OnClientVehicleHealthStateChanged");

	Params::BP_Motorbike_SideCart_C_OnClientVehicleHealthStateChanged Parms{};

	Parms.VehicleHealthState_0 = VehicleHealthState_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Motorbike_SideCart.BP_Motorbike_SideCart_C.UpdateExhaustFx
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UParticleSystemComponent*         PSCExhaust_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Motorbike_SideCart_C::UpdateExhaustFx(class UParticleSystemComponent* PSCExhaust_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_Motorbike_SideCart_C", "UpdateExhaustFx");

	Params::BP_Motorbike_SideCart_C_UpdateExhaustFx Parms{};

	Parms.PSCExhaust_0 = PSCExhaust_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

