#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MapMarkerWidget

#include "Basic.hpp"

#include "BP_MapMarkerWidget_classes.hpp"
#include "BP_MapMarkerWidget_parameters.hpp"


namespace SDK
{

// Function BP_MapMarkerWidget.BP_MapMarkerWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_MapMarkerWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_MapMarkerWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MapMarkerWidget.BP_MapMarkerWidget_C.ExecuteUbergraph_BP_MapMarkerWidget
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_MapMarkerWidget_C::ExecuteUbergraph_BP_MapMarkerWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_MapMarkerWidget_C", "ExecuteUbergraph_BP_MapMarkerWidget");

	Params::BP_MapMarkerWidget_C_ExecuteUbergraph_BP_MapMarkerWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MapMarkerWidget.BP_MapMarkerWidget_C.ResetMarkerSwitcher
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_MapMarkerWidget_C::ResetMarkerSwitcher()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_MapMarkerWidget_C", "ResetMarkerSwitcher");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MapMarkerWidget.BP_MapMarkerWidget_C.SetTacticalMarkerSwitcherByIndex
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_MapMarkerWidget_C::SetTacticalMarkerSwitcherByIndex(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("BP_MapMarkerWidget_C", "SetTacticalMarkerSwitcherByIndex");

	Params::BP_MapMarkerWidget_C_SetTacticalMarkerSwitcherByIndex Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

