#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bp_market_appearance

#include "Basic.hpp"

#include "BP_STRUCT_MarketAppearanceUI_AvatarModelInfo_structs.hpp"
#include "Client_classes.hpp"


namespace SDK
{

// ScriptBlueprintGeneratedClass bp_market_appearance.bp_market_appearance_C
// 0x0080 (0x0468 - 0x03E8)
class Abp_market_appearance_C final : public ALuaClassObj
{
public:
	class UScriptContextComponent*                Generated_ScriptContext;                           // 0x03E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	TArray<int32>                                 BP_ARRAY_MarketAppearanceUISelectList;             // 0x03F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor)
	TArray<int32>                                 BP_ARRAY_MarketAppearanceUIWearList;               // 0x0400(0x0010)(Edit, BlueprintVisible, ZeroConstructor)
	int32                                         BP_MarketAppearanceUICurSelectItemNum;             // 0x0410(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_414[0x4];                                      // 0x0414(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 BP_ARRAY_MarketAppearanceUI_AvatarChange_ResId_List; // 0x0418(0x0010)(Edit, BlueprintVisible, ZeroConstructor)
	uint8                                         BP_MarketAppearanceUINotOwn : 1;                   // 0x0428(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_429[0x3];                                      // 0x0429(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         BP_MarketAppearanceUIBuyIdx;                       // 0x042C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         BP_MarketAppearanceUI_ReloadDonotJump : 1;         // 0x0430(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_431[0x3];                                      // 0x0431(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         BP_MarketAppearanceUISelectTypeIdx;                // 0x0434(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         BP_MarketAppearanceUI_AvatarPuton : 1;             // 0x0438(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_439[0x7];                                      // 0x0439(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBP_STRUCT_MarketAppearanceUI_AvatarModelInfo BP_STRUCT_MarketAppearanceUI_AvatarModelInfo; // 0x0440(0x0020)(Edit, BlueprintVisible, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void EventMarketAppearanceUIResetAvatar();
	void EventMarketAppearanceUIResetAvatar_NoFetch();
	void EventMarketAppearanceUIGetCurrentSelectNum();
	void EventMarketAppearanceUIGetCurrentSelectNum_NoFetch();
	void EventMarketAppearanceUIToggleOwn();
	void EventMarketAppearanceUIToggleOwn_NoFetch();
	void EventMarketAppearanceUISelect();
	void EventMarketAppearanceUISelect_NoFetch();
	void EventMarketAppearanceUISelectType();
	void EventMarketAppearanceUISelectType_NoFetch();
	void EventMarketAppearanceUIBuy();
	void EventMarketAppearanceUIBuy_NoFetch();
	void EventMarketAppearanceUIBatchBuy();
	void EventMarketAppearanceUIBatchBuy_NoFetch();
	void EventMarketAppearanceUISwitchGender();
	void EventMarketAppearanceUISwitchGender_NoFetch();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("bp_market_appearance_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"bp_market_appearance_C")
	}
	static class Abp_market_appearance_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Abp_market_appearance_C>();
	}
};

}

