#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerLobbyPawn

#include "Basic.hpp"

#include "BP_STRUCT_Item_type_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "ShadowTrackerExtra_structs.hpp"
#include "Basic_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.ExecuteUbergraph_BP_PlayerLobbyPawn
// 0x00F8 (0x00F8 - 0x0000)
struct BP_PlayerLobbyPawn_C_ExecuteUbergraph_BP_PlayerLobbyPawn final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_GetUserWidgetObject_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_IsValid_ReturnValue : 1;                  // 0x0010(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_LitePCLobbyNameTag_C*               K2Node_DynamicCast_AsBP_Lite_PCLobby_Name_Tag;     // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess : 1;                   // 0x0020(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue2 : 1;                 // 0x0021(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue3 : 1;                 // 0x0022(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue4 : 1;                 // 0x0023(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue5 : 1;                 // 0x0024(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Event_ItemId;                               // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_Event_bHost : 1;                            // 0x002C(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         K2Node_Event_bReady : 1;                           // 0x002D(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         K2Node_Event_InVal : 1;                            // 0x002E(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_2F[0x1];                                       // 0x002F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Event_NewNickName;                          // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ERatingRankType                               K2Node_Event_NewRankType;                          // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_IsValid_ReturnValue6 : 1;                 // 0x0041(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsLogout_ReturnValue : 1;                 // 0x0042(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue7 : 1;                 // 0x0043(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         K2Node_Event_bShow : 1;                            // 0x0044(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_45[0x3];                                       // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ULobby_AnimBP_C*                        K2Node_DynamicCast_AsLobby_Anim_BP;                // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess2 : 1;                  // 0x0058(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue8 : 1;                 // 0x0059(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue9 : 1;                 // 0x005A(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue10 : 1;                // 0x005B(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	int32                                         K2Node_Event_InVoiceState;                         // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_IsValid_ReturnValue11 : 1;                // 0x0060(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_61[0x3];                                       // 0x0061(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetSlotId_ReturnValue;                    // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeLocation_SweepHitResult;    // 0x0068(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	uint8                                         CallFunc_EqualEqual_IntInt_ReturnValue : 1;        // 0x00F0(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.SetVoiceState
// 0x0004 (0x0004 - 0x0000)
struct BP_PlayerLobbyPawn_C_SetVoiceState final
{
public:
	int32                                         InVoiceState;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.SetState
// 0x0001 (0x0001 - 0x0000)
struct BP_PlayerLobbyPawn_C_SetState final
{
public:
	uint8                                         bShow : 1;                                         // 0x0000(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.SetRankEmblem
// 0x0001 (0x0001 - 0x0000)
struct BP_PlayerLobbyPawn_C_SetRankEmblem final
{
public:
	ERatingRankType                               NewRankType;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.SetNickName
// 0x0010 (0x0010 - 0x0000)
struct BP_PlayerLobbyPawn_C_SetNickName final
{
public:
	class FString                                 NewNickName;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.HideEquippedWeapon
// 0x0001 (0x0001 - 0x0000)
struct BP_PlayerLobbyPawn_C_HideEquippedWeapon final
{
public:
	uint8                                         InVal : 1;                                         // 0x0000(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.UpdateEquipedWeapon
// 0x0004 (0x0004 - 0x0000)
struct BP_PlayerLobbyPawn_C_UpdateEquipedWeapon final
{
public:
	int32                                         ItemID;                                            // 0x0000(0x0004)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.SetHost
// 0x0001 (0x0001 - 0x0000)
struct BP_PlayerLobbyPawn_C_SetHost final
{
public:
	uint8                                         bHost : 1;                                         // 0x0000(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.SetReady
// 0x0001 (0x0001 - 0x0000)
struct BP_PlayerLobbyPawn_C_SetReady final
{
public:
	uint8                                         bReady : 1;                                        // 0x0000(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.GetHiddenFlags
// 0x0028 (0x0028 - 0x0000)
struct BP_PlayerLobbyPawn_C_GetHiddenFlags final
{
public:
	int32                                         resID_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EAvatarSlotType>                       hiddenFlags;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor)
	class UBackpackAvatarHandle*                  CallFunc_GetBattleItemFromResID_ReturnValue;       // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_IsValid_ReturnValue : 1;                  // 0x0020(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.GetBPID
// 0x0268 (0x0268 - 0x0000)
struct BP_PlayerLobbyPawn_C_GetBPID final
{
public:
	int32                                         RowName;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BPID;                                              // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBP_STRUCT_Item_type                   CallFunc_GetDataTableRowFromName_OutRow;           // 0x0020(0x0240)(HasGetValueTypeHash)
	uint8                                         CallFunc_GetDataTableRowFromName_ReturnValue : 1;  // 0x0260(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.GetBattleItemFromResID
// 0x0058 (0x0058 - 0x0000)
struct BP_PlayerLobbyPawn_C_GetBattleItemFromResID final
{
public:
	int32                                         RowName;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBackpackAvatarHandle*                  ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FItemDefineID                          CallFunc_GenerateItemDefineIDByItemTableIDWithRandomInstanceID_ReturnValue; // 0x0010(0x0018)(NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetBPID_BPID;                             // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUAELoadedClassManager*                 CallFunc_Get_ReturnValue;                          // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_GetClass_ReturnValue;                     // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_ClassDynamicCast_AsBackpack_Avatar_Handle;  // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_ClassDynamicCast_bSuccess : 1;              // 0x0048(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBackpackAvatarHandle*                  CallFunc_SpawnObject_ReturnValue;                  // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.Set Anim Pose
// 0x0020 (0x0020 - 0x0000)
struct BP_PlayerLobbyPawn_C_Set_Anim_Pose final
{
public:
	uint8                                         CallFunc_IsValid_ReturnValue : 1;                  // 0x0000(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ULobby_AnimBP_C*                        K2Node_DynamicCast_AsLobby_Anim_BP;                // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess : 1;                   // 0x0018(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue2 : 1;                 // 0x0019(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	EAnimWeaponType                               CallFunc_GetAnimWeaponType_ReturnValue;            // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.WeaponAttachComponent
// 0x0010 (0x0010 - 0x0000)
struct alignas(0x08) BP_PlayerLobbyPawn_C_WeaponAttachComponent final
{
public:
	class FName                                   CallFunc_GetWeaponAttachSocket_ReturnValue;        // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_IsValid_ReturnValue : 1;                  // 0x0008(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.SpawnWeapon
// 0x0180 (0x0180 - 0x0000)
struct BP_PlayerLobbyPawn_C_SpawnWeapon final
{
public:
	int32                                         WeaponId;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUAELoadedClassManager*                 CallFunc_Get_ReturnValue;                          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetMeshPath_ReturnValue;                  // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	uint8                                         CallFunc_IsValid_ReturnValue : 1;                  // 0x0020(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSoftObjectPath                        CallFunc_MakeSoftObjectPath_ReturnValue;           // 0x0028(0x0018)(HasGetValueTypeHash)
	class UObject*                                CallFunc_GetAssetByAssetReference_ReturnValue;     // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UStaticMesh*                            K2Node_DynamicCast_AsStatic_Mesh;                  // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess : 1;                   // 0x0050(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMesh*                          K2Node_DynamicCast_AsSkeletal_Mesh;                // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess2 : 1;                  // 0x0060(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUAELoadedClassManager*                 CallFunc_Get_ReturnValue2;                         // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBackpackBlueprintUtils_BP_C*           CallFunc_SpawnObject_ReturnValue;                  // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetParentID_ReturnValue;                  // 0x0078(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	uint8                                         CallFunc_IsValid_ReturnValue2 : 1;                 // 0x0088(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_89[0x3];                                       // 0x0089(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_StringToInt_ReturnValue;             // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0090(0x0030)(IsPlainOldData, NoDestructor)
	class UBattleItemHandleBase*                  CallFunc_CreateBattleItemHandle_Default_BattleItemHandle; // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C8[0x8];                                       // 0x00C8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue2;               // 0x00D0(0x0030)(IsPlainOldData, NoDestructor)
	class UBattleItemHandle_MainWeaponPC_C*       K2Node_DynamicCast_AsBattle_Item_Handle_Main_Weapon_PC; // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess3 : 1;                  // 0x0108(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_109[0x7];                                      // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBattleItemHandle_MeleeWeapon_C*        K2Node_DynamicCast_AsBattle_Item_Handle_Melee_Weapon; // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess4 : 1;                  // 0x0118(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue2; // 0x0128(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASTExtraWeapon*                         CallFunc_FinishSpawningActor_ReturnValue;          // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASTExtraWeapon*                         CallFunc_FinishSpawningActor_ReturnValue2;         // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_IsValid_ReturnValue3 : 1;                 // 0x0140(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_141[0x7];                                      // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMeshComponent*                   CallFunc_GetWeaponStaticMeshComponent_ReturnValue; // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 CallFunc_GetWeaponSkeletalMeshComponent_ReturnValue; // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_SetStaticMesh_ReturnValue : 1;            // 0x0158(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue4 : 1;                 // 0x0159(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValidClass_ReturnValue : 1;             // 0x015A(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValidClass_ReturnValue2 : 1;            // 0x015B(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue5 : 1;                 // 0x015C(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue6 : 1;                 // 0x015D(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue7 : 1;                 // 0x015E(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_15F[0x1];                                      // 0x015F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetPathName_ReturnValue;                  // 0x0160(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	uint8                                         CallFunc_Contains_ReturnValue : 1;                 // 0x0170(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_Contains_ReturnValue2 : 1;                // 0x0171(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_Contains_ReturnValue3 : 1;                // 0x0172(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_Contains_ReturnValue4 : 1;                // 0x0173(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_BooleanOR_ReturnValue : 1;                // 0x0174(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_BooleanOR_ReturnValue2 : 1;               // 0x0175(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_BooleanOR_ReturnValue3 : 1;               // 0x0176(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.SetWeaponSkin
// 0x0058 (0x0058 - 0x0000)
struct BP_PlayerLobbyPawn_C_SetWeaponSkin final
{
public:
	int32                                         SkinID;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_IsValid_ReturnValue : 1;                  // 0x0004(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue2 : 1;                 // 0x0005(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UUAELoadedClassManager*                 CallFunc_Get_ReturnValue;                          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetSkinPath_ReturnValue;                  // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FSoftObjectPath                        CallFunc_MakeSoftObjectPath_ReturnValue;           // 0x0020(0x0018)(HasGetValueTypeHash)
	class UObject*                                CallFunc_GetAssetByAssetReference_ReturnValue;     // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_IsValid_ReturnValue3 : 1;                 // 0x0040(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstance*                      K2Node_DynamicCast_AsMaterial_Instance;            // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess : 1;                   // 0x0050(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue4 : 1;                 // 0x0051(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function BP_PlayerLobbyPawn.BP_PlayerLobbyPawn_C.GetSkinEmoteId
// 0x02B0 (0x02B0 - 0x0000)
struct BP_PlayerLobbyPawn_C_GetSkinEmoteId final
{
public:
	TArray<int32>                                 ItemIds;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)
	class FName                                   ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Array_Index_Variable;                       // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ___int_Loop_Counter_Variable;                      // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Get_Item;                           // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	uint8                                         CallFunc_Less_IntInt_ReturnValue : 1;              // 0x0038(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBP_STRUCT_Item_type                   CallFunc_GetDataTableRowFromName_OutRow;           // 0x0048(0x0240)(HasGetValueTypeHash)
	uint8                                         CallFunc_GetDataTableRowFromName_ReturnValue : 1;  // 0x0288(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_289[0x3];                                      // 0x0289(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x028C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue2;            // 0x0290(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	uint8                                         CallFunc_Conv_IntToBool_ReturnValue : 1;           // 0x02A0(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_2A1[0x7];                                      // 0x02A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Conv_StringToName_ReturnValue2;           // 0x02A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

