#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_STRUCT_MasterPrivilegeDescItem

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct BP_STRUCT_MasterPrivilegeDescItem.BP_STRUCT_MasterPrivilegeDescItem
// 0x0020 (0x0020 - 0x0000)
struct FBP_STRUCT_MasterPrivilegeDescItem final
{
public:
	class FString                                 iconUrl_0_B55443FA43D55D7155D8579A2B2B71A2;        // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 iconDesc_1_BAF430B4422F20D1FF90A6A2F6D40D20;       // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
};

}

