#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_STRUCT_RoomSelfInfo

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct BP_STRUCT_RoomSelfInfo.BP_STRUCT_RoomSelfInfo
// 0x0060 (0x0060 - 0x0000)
struct FBP_STRUCT_RoomSelfInfo final
{
public:
	class FString                                 openid_0_0A1285C04EE96896A10B3EA4F4DFD669;         // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         level_1_1C45BD134A290840F10DBFB768BB9565;          // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 name_2_DEDDBA474442D739A7E6ABB8774E692B;           // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         svr_3_5FE9036844753186FBFDE2A62D64479E;            // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         gender_4_F2F5EAF04D5CA44A0D02BDA3C9143AC1;         // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         frame_level_5_496CB4FE48F43AF05508278EAEB8CF81;    // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         isRoomMaster_6_759A24614B691043C28C9F934BD264DD : 1; // 0x0034(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         pos_7_54DF2FB64C05B904666FCEBE75A48444;            // 0x0038(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 state_8_6C5A3C9648FCA56DFFD9ACA85AB3BC43;          // 0x0040(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 head_url_9_F203D8474DA7BCBD70D59DAB70E67875;       // 0x0050(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
};

}

