#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_STRUCT_FPPCombatScoreInfo

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct BP_STRUCT_FPPCombatScoreInfo.BP_STRUCT_FPPCombatScoreInfo
// 0x0030 (0x0030 - 0x0000)
struct FBP_STRUCT_FPPCombatScoreInfo final
{
public:
	class FString                                 role_rankscore_0_3708C4801F6F9FDA682763E00E5B3805; // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 role_score_1_1F65998076D27D445FA092BA02BFAFF5;     // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 role_killscore_2_1AEDA4802BBF7C0644832EAE0C4B1E85; // 0x0020(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
};

}

