#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_STRUCT_CorpsAwardInfo

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct BP_STRUCT_CorpsAwardInfo.BP_STRUCT_CorpsAwardInfo
// 0x0038 (0x0038 - 0x0000)
struct FBP_STRUCT_CorpsAwardInfo final
{
public:
	int32                                         award_num_0_1537077C47AEC797F80CCCBC976456DE;      // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         my_activity_1_97501E6346B75FF2F6E851865C6E0725;    // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         icon_2_A7C79E7E4B854F8690301ABCF041E4FA;           // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         award_id_3_D7E830274CD79A0523736E935E87BCFB;       // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         last_activity_4_83D45C884EB1120C634DAF988AAAADC7;  // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         last_rank_14_3883973148EE6A3F009868AF675EF09E;     // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         is_week_7_2C9D09E340E82D73BA455496041E808D : 1;    // 0x0018(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         is_get_award_10_26FC78004619A80A39E7D72C0478F4A4 : 1; // 0x0019(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_1A[0x2];                                       // 0x001A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         need_activity_11_11E657C0207B13EB48D3D0F40F7C6B69; // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 coprs_name_12_7C340780596DBDA26957126A087DD735;    // 0x0020(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         last_rank_per_15_6552770067A9CB745EE7A7B305CEFEE2; // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

