#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_STRUCT_VehicleBPTable_type

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct BP_STRUCT_VehicleBPTable_type.BP_STRUCT_VehicleBPTable_type
// 0x0028 (0x0028 - 0x0000)
struct FBP_STRUCT_VehicleBPTable_type final
{
public:
	int32                                         ID_0_0D9DF74051BBD583279703B701F172E4;             // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Path_2_2F72974026FE3BC32110651501735958;           // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CName_3_138BC5001BE2FE5E5E66B36807255925;          // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
};

}

