#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bp_wardrobe

#include "Basic.hpp"

#include "BP_STRUCT_WardrobeChangedItemData_structs.hpp"
#include "BP_STRUCT_WardrobeItemInfo_structs.hpp"
#include "Client_classes.hpp"
#include "BP_STRUCT_WardrobeClickedItemData_structs.hpp"


namespace SDK
{

// ScriptBlueprintGeneratedClass bp_wardrobe.bp_wardrobe_C
// 0x0180 (0x0558 - 0x03D8)
class Abp_wardrobe_C final : public ALuaClassObj
{
public:
	class UScriptContextComponent*                Generated_ScriptContext;                           // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)
	int32                                         BP_PageRedPointMask;                               // 0x03E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BP_LastTabType;                                    // 0x03E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 BP_WardrobeDiamond;                                // 0x03E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	TArray<struct FBP_STRUCT_WardrobeItemInfo>    BP_ARRAY_Wardrobe_SourceBookItemList;              // 0x03F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor)
	struct FBP_STRUCT_WardrobeClickedItemData     BP_STRUCT_WardrobeClickedItemData;                 // 0x0408(0x0038)(Edit, BlueprintVisible, HasGetValueTypeHash)
	class FString                                 BP_WardrobeGold;                                   // 0x0440(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	struct FBP_STRUCT_WardrobeChangedItemData     BP_STRUCT_WardrobeChangedItemData;                 // 0x0450(0x0038)(Edit, BlueprintVisible, HasGetValueTypeHash)
	uint8                                         BP_Wardrobe_IsShowDecomposeButton : 1;             // 0x0488(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_489[0x7];                                      // 0x0489(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 BP_Wardrobe_DecomposeItemInsID;                    // 0x0490(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         BP_WARDROBE_Jump_Item_resID;                       // 0x04A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BP_CurPageTabType;                                 // 0x04A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BP_LastPageType;                                   // 0x04A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BP_CurTabType;                                     // 0x04AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BP_ChangeTabType;                                  // 0x04B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BP_Wardrobe_BG_resID;                              // 0x04B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         BP_Wardrobe_IsShowJumpToExchange : 1;              // 0x04B8(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_4B9[0x3];                                      // 0x04B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         BP_ChangeTabIcon;                                  // 0x04BC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 BP_String_Wardrobe_RemainTime;                     // 0x04C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	TArray<struct FBP_STRUCT_WardrobeItemInfo>    BP_ARRAY_WardrobeItemList;                         // 0x04D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor)
	uint8                                         BP_Wardrobe_BG_showPutOn : 1;                      // 0x04E0(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_4E1[0x3];                                      // 0x04E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         BP_ChangePageTabType;                              // 0x04E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<int32>                                 BP_ARRAY_CurPageTabIcon;                           // 0x04E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor)
	uint8                                         BP_Wardrobe_IsShowUseButton : 1;                   // 0x04F8(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_4F9[0x7];                                      // 0x04F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBP_STRUCT_WardrobeItemInfo            BP_STRUCT_WardrobeItemInfo;                        // 0x0500(0x0038)(Edit, BlueprintVisible, HasGetValueTypeHash)
	class FString                                 BP_Sell_id;                                        // 0x0538(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         BP_TabRedPointMask;                                // 0x0548(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54C[0x4];                                      // 0x054C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0550(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void EventWardrobeClickJump();
	void EventWardrobeClickJump_NoFetch();
	void EventWardrobeClickJumpToExchange();
	void EventWardrobeClickJumpToExchange_NoFetch();
	void EventWardrobeClickDecomposeItem();
	void EventWardrobeClickDecomposeItem_NoFetch();
	void EventChangeWardrodbeTab();
	void EventChangeWardrodbeTab_NoFetch();
	void EventWardrobeClickItem();
	void EventWardrobeClickItem_NoFetch();
	void EventWardrobeSell();
	void EventWardrobeSell_NoFetch();
	void EventHideWardrodbe();
	void EventHideWardrodbe_NoFetch();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("bp_wardrobe_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"bp_wardrobe_C")
	}
	static class Abp_wardrobe_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Abp_wardrobe_C>();
	}
};

}

