#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CH_SceneCapture

#include "Basic.hpp"

#include "ShadowTrackerExtra_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function CH_SceneCapture.CH_SceneCapture_C.ExecuteUbergraph_CH_SceneCapture
// 0x0010 (0x0010 - 0x0000)
struct CH_SceneCapture_C_ExecuteUbergraph_CH_SceneCapture final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0004(0x000C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function CH_SceneCapture.CH_SceneCapture_C.SetAnimWeaponPose
// 0x0001 (0x0001 - 0x0000)
struct CH_SceneCapture_C_SetAnimWeaponPose final
{
public:
	EAnimWeaponType                               WeaponType_0;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

