#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChildOptionTitleWidget

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ChildOptionTitleWidget.ChildOptionTitleWidget_C
// 0x0028 (0x0240 - 0x0218)
class UChildOptionTitleWidget_C final : public UUserWidget
{
public:
	class UImage*                                 Image_0;                                           // 0x0218(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_0;                                       // 0x0220(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   DisplayTitleText;                                  // 0x0228(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)

public:
	class FText GetText_0();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ChildOptionTitleWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ChildOptionTitleWidget_C")
	}
	static class UChildOptionTitleWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChildOptionTitleWidget_C>();
	}
};

}

