#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EBackPackDragOrigin

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EBackPackDragOrigin.EBackPackDragOrigin
// NumValues: 0x000A
enum class EBackPackDragOrigin : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator6                           = 3,
	NewEnumerator5                           = 4,
	NewEnumerator14                          = 5,
	NewEnumerator3                           = 6,
	NewEnumerator4                           = 7,
	NewEnumerator8                           = 8,
	EBackPackDragOrigin_MAX                  = 9,
};

}

