#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EConsumableListSortMode

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EConsumableListSortMode.EConsumableListSortMode
// NumValues: 0x0007
enum class EConsumableListSortMode : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	NewEnumerator5                           = 5,
	EConsumableListSortMode_MAX              = 6,
};

}

