#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EmoteComponent_BP

#include "Basic.hpp"

#include "EmoteComponent_BP_classes.hpp"
#include "EmoteComponent_BP_parameters.hpp"


namespace SDK
{

// Function EmoteComponent_BP.EmoteComponent_BP_C.ExecuteUbergraph_EmoteComponent_BP
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UEmoteComponent_BP_C::ExecuteUbergraph_EmoteComponent_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("EmoteComponent_BP_C", "ExecuteUbergraph_EmoteComponent_BP");

	Params::EmoteComponent_BP_C_ExecuteUbergraph_EmoteComponent_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EmoteComponent_BP.EmoteComponent_BP_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UEmoteComponent_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("EmoteComponent_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EmoteComponent_BP.EmoteComponent_BP_C.GetEmoteDataByName
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             EmoteName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FEmoteDBDataRow                  ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEmoteDBDataRow UEmoteComponent_BP_C::GetEmoteDataByName(class FName EmoteName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("EmoteComponent_BP_C", "GetEmoteDataByName");

	Params::EmoteComponent_BP_C_GetEmoteDataByName Parms{};

	Parms.EmoteName = EmoteName;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function EmoteComponent_BP.EmoteComponent_BP_C.IsAbleGetEmoteDataByName
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             EmoteName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

uint8 UEmoteComponent_BP_C::IsAbleGetEmoteDataByName(class FName EmoteName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("EmoteComponent_BP_C", "IsAbleGetEmoteDataByName");

	Params::EmoteComponent_BP_C_IsAbleGetEmoteDataByName Parms{};

	Parms.EmoteName = EmoteName;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function EmoteComponent_BP.EmoteComponent_BP_C.ReadEmoteDataRowPC
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UEmoteComponent_BP_C::ReadEmoteDataRowPC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("EmoteComponent_BP_C", "ReadEmoteDataRowPC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EmoteComponent_BP.EmoteComponent_BP_C.GetEmoteHandle
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ItemID                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UBackpackEmoteHandle*             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UBackpackEmoteHandle* UEmoteComponent_BP_C::GetEmoteHandle(int32 ItemID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("EmoteComponent_BP_C", "GetEmoteHandle");

	Params::EmoteComponent_BP_C_GetEmoteHandle Parms{};

	Parms.ItemID = ItemID;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

