#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Global_Voice

#include "Basic.hpp"

#include "Global_Voice_classes.hpp"
#include "Global_Voice_parameters.hpp"


namespace SDK
{

// Function Global_Voice.Global_Voice_C.ExecuteUbergraph_Global_Voice
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGlobal_Voice_C::ExecuteUbergraph_Global_Voice(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "ExecuteUbergraph_Global_Voice");

	Params::Global_Voice_C_ExecuteUbergraph_Global_Voice Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Global_Voice.Global_Voice_C.OnUploadSpeechToTextFailed
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnUploadSpeechToTextFailed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnUploadSpeechToTextFailed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnUploadRecordFileFailed
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnUploadRecordFileFailed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnUploadRecordFileFailed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnApplicationDeactivated
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnApplicationDeactivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnApplicationDeactivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnTryStopPlayRecordVoice
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnTryStopPlayRecordVoice()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnTryStopPlayRecordVoice");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnTeamStateChanged
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnTeamStateChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnTeamStateChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.BndEvt__btn_mic_off_K2Node_ComponentBoundEvent_104_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UGlobal_Voice_C::BndEvt__btn_mic_off_K2Node_ComponentBoundEvent_104_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "BndEvt__btn_mic_off_K2Node_ComponentBoundEvent_104_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnVoiceSpeakerOpenChanged
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnVoiceSpeakerOpenChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnVoiceSpeakerOpenChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnVoiceMicOpenChanged
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnVoiceMicOpenChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnVoiceMicOpenChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.BndEvt__btn_mic_on_K2Node_ComponentBoundEvent_58_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UGlobal_Voice_C::BndEvt__btn_mic_on_K2Node_ComponentBoundEvent_58_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "BndEvt__btn_mic_on_K2Node_ComponentBoundEvent_58_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.BndEvt__btn_voice_off_K2Node_ComponentBoundEvent_41_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UGlobal_Voice_C::BndEvt__btn_voice_off_K2Node_ComponentBoundEvent_41_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "BndEvt__btn_voice_off_K2Node_ComponentBoundEvent_41_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.BndEvt__btn_voice_on_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UGlobal_Voice_C::BndEvt__btn_voice_on_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "BndEvt__btn_voice_on_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnGameStageChanged
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnGameStageChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnGameStageChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnUploadSpeechToTextComplete
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnUploadSpeechToTextComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnUploadSpeechToTextComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnUploadRecordFileComplete
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnUploadRecordFileComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnUploadRecordFileComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnTryCancelRecordVoice
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnTryCancelRecordVoice()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnTryCancelRecordVoice");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnTryStopRecordVoice
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnTryStopRecordVoice()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnTryStopRecordVoice");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnTryStartRecordVoice
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnTryStartRecordVoice()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnTryStartRecordVoice");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnApplyMessageKeyComplete
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnApplyMessageKeyComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnApplyMessageKeyComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnDownloadFileComplete
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnDownloadFileComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnDownloadFileComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnClearDownloadFailedNotify
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnClearDownloadFailedNotify()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnClearDownloadFailedNotify");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnTryDownloadVoiceRecord
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnTryDownloadVoiceRecord()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnTryDownloadVoiceRecord");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnClearSpeechToTextResend
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnClearSpeechToTextResend()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnClearSpeechToTextResend");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnRequireSpeechToTextResend
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnRequireSpeechToTextResend()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnRequireSpeechToTextResend");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnAfterRequireSpeechToText
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnAfterRequireSpeechToText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnAfterRequireSpeechToText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnClearUploadResend
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnClearUploadResend()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnClearUploadResend");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnRequireUploadResend
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnRequireUploadResend()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnRequireUploadResend");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnAfterRequireUpload
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnAfterRequireUpload()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnAfterRequireUpload");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnClearAuthResend
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnClearAuthResend()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnClearAuthResend");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnRequireAuthResend
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnRequireAuthResend()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnRequireAuthResend");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnAfterRequireAuth
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnAfterRequireAuth()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnAfterRequireAuth");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnGVoiceInited
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnGVoiceInited()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnGVoiceInited");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnClearRoleInfo
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnClearRoleInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnClearRoleInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnResetRoleInfo
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnResetRoleInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnResetRoleInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnVoiceModeChanged
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnVoiceModeChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnVoiceModeChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnTeamVoiceRoomChanged
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnTeamVoiceRoomChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnTeamVoiceRoomChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnJoinVoiceRoomSuccess
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnJoinVoiceRoomSuccess()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnJoinVoiceRoomSuccess");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnQuitVoiceRoomSuccess
// (BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnQuitVoiceRoomSuccess()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnQuitVoiceRoomSuccess");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UGlobal_Voice_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.SyncLuaData
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::SyncLuaData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "SyncLuaData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.SyncPushLuaData
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::SyncPushLuaData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "SyncPushLuaData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.ResetTeamVoice
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::ResetTeamVoice()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "ResetTeamVoice");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.ResetGVoiceMode
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Mode                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGlobal_Voice_C::ResetGVoiceMode(int32 Mode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "ResetGVoiceMode");

	Params::Global_Voice_C_ResetGVoiceMode Parms{};

	Parms.Mode = Mode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Global_Voice.Global_Voice_C.RequireGVoiceAuthEntry
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::RequireGVoiceAuthEntry()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "RequireGVoiceAuthEntry");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.RequireGVoiceUploadEntry
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::RequireGVoiceUploadEntry()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "RequireGVoiceUploadEntry");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.RequireGVoiceSpeechToTextEntry
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::RequireGVoiceSpeechToTextEntry()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "RequireGVoiceSpeechToTextEntry");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.RequireGVoiceAuth
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::RequireGVoiceAuth()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "RequireGVoiceAuth");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.RequireGVoiceUpload
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::RequireGVoiceUpload()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "RequireGVoiceUpload");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.RequireGVoiceSpeechToText
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::RequireGVoiceSpeechToText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "RequireGVoiceSpeechToText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.ClearResendProcedure
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::ClearResendProcedure()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "ClearResendProcedure");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.ProcessVoiceProcedure
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8*                                  Output                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGlobal_Voice_C::ProcessVoiceProcedure(uint8* Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "ProcessVoiceProcedure");

	Params::Global_Voice_C_ProcessVoiceProcedure Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;
}


// Function Global_Voice.Global_Voice_C.ClearGVoiceAuthResendEntry
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::ClearGVoiceAuthResendEntry()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "ClearGVoiceAuthResendEntry");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.ClearGVoiceUploadResendEntry
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::ClearGVoiceUploadResendEntry()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "ClearGVoiceUploadResendEntry");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.ClearGVoiceSpeechToTextResendEntry
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::ClearGVoiceSpeechToTextResendEntry()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "ClearGVoiceSpeechToTextResendEntry");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.AddProcedureTimer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FTimerHandle&              Handle                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// int32                                   resendType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   IsStop                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGlobal_Voice_C::AddProcedureTimer(const struct FTimerHandle& Handle, int32 resendType, uint8 IsStop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "AddProcedureTimer");

	Params::Global_Voice_C_AddProcedureTimer Parms{};

	Parms.Handle = std::move(Handle);
	Parms.resendType = resendType;
	Parms.IsStop = IsStop;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Global_Voice.Global_Voice_C.GetProcedureTimer
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   stopTimer                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FTimerHandle*                    Output                                                 (Parm, OutParm, NoDestructor)

void UGlobal_Voice_C::GetProcedureTimer(int32 Type, uint8 stopTimer, struct FTimerHandle* Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "GetProcedureTimer");

	Params::Global_Voice_C_GetProcedureTimer Parms{};

	Parms.Type = Type;
	Parms.stopTimer = stopTimer;

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = std::move(Parms.Output);
}


// Function Global_Voice.Global_Voice_C.RetrieveGVoiceOffline
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::RetrieveGVoiceOffline()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "RetrieveGVoiceOffline");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.LeaveGVoiceOffline
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::LeaveGVoiceOffline()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "LeaveGVoiceOffline");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.RecoverGVoiceRealtime
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::RecoverGVoiceRealtime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "RecoverGVoiceRealtime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.RequireGVoiceDownload
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::RequireGVoiceDownload()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "RequireGVoiceDownload");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.PlayDownloadFile
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::PlayDownloadFile()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "PlayDownloadFile");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.StopPlayRecordFile
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::StopPlayRecordFile()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "StopPlayRecordFile");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.StartRecordVoice
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::StartRecordVoice()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "StartRecordVoice");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.StopRecordVoice
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   Cancel                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGlobal_Voice_C::StopRecordVoice(uint8 Cancel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "StopRecordVoice");

	Params::Global_Voice_C_StopRecordVoice Parms{};

	Parms.Cancel = Cancel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Global_Voice.Global_Voice_C.RefreshStageUI
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::RefreshStageUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "RefreshStageUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.RefreshLobbyUI
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::RefreshLobbyUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "RefreshLobbyUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.ChangeMicState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGlobal_Voice_C::ChangeMicState(uint8 State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "ChangeMicState");

	Params::Global_Voice_C_ChangeMicState Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Global_Voice.Global_Voice_C.ChangeSpeakerState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   Open                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGlobal_Voice_C::ChangeSpeakerState(uint8 Open)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "ChangeSpeakerState");

	Params::Global_Voice_C_ChangeSpeakerState Parms{};

	Parms.Open = Open;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Global_Voice.Global_Voice_C.RefreshTeamUI
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::RefreshTeamUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "RefreshTeamUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.SyncTeamupState
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::SyncTeamupState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "SyncTeamupState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.RefreshMicUI
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::RefreshMicUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "RefreshMicUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.RefreshSpeakerUI
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::RefreshSpeakerUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "RefreshSpeakerUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.ClearAllTimers
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::ClearAllTimers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "ClearAllTimers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnClickMicOn
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnClickMicOn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnClickMicOn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnClickMicOff
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnClickMicOff()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnClickMicOff");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnClickSpeakerOn
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnClickSpeakerOn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnClickSpeakerOn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnClickSpeakerOff
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnClickSpeakerOff()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnClickSpeakerOff");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.CheckVoiceMessageInited
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8*                                  Ret                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGlobal_Voice_C::CheckVoiceMessageInited(uint8* Ret)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "CheckVoiceMessageInited");

	Params::Global_Voice_C_CheckVoiceMessageInited Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Ret != nullptr)
		*Ret = Parms.Ret;
}


// Function Global_Voice.Global_Voice_C.FadeInBGM
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::FadeInBGM()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "FadeInBGM");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.FadeOutBGM
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::FadeOutBGM()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "FadeOutBGM");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.StopPlayRecordFileAndRecoverBGM
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::StopPlayRecordFileAndRecoverBGM()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "StopPlayRecordFileAndRecoverBGM");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnTryCloseMic
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnTryCloseMic()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnTryCloseMic");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnUploadRecordFailed
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnUploadRecordFailed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnUploadRecordFailed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.UIShow
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::UIShow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "UIShow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.UIHide
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::UIHide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "UIHide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.TickVoiceRoom
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::TickVoiceRoom()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "TickVoiceRoom");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.OnTryCloseSpeaker
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::OnTryCloseSpeaker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "OnTryCloseSpeaker");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Global_Voice.Global_Voice_C.ChangeMicphoneFlag
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   Open                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGlobal_Voice_C::ChangeMicphoneFlag(uint8 Open)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "ChangeMicphoneFlag");

	Params::Global_Voice_C_ChangeMicphoneFlag Parms{};

	Parms.Open = Open;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Global_Voice.Global_Voice_C.ChangeSpeakerFlag
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   Open                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGlobal_Voice_C::ChangeSpeakerFlag(uint8 Open)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "ChangeSpeakerFlag");

	Params::Global_Voice_C_ChangeSpeakerFlag Parms{};

	Parms.Open = Open;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Global_Voice.Global_Voice_C.SyncOneData
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    prop                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UGlobal_Voice_C::SyncOneData(const class FString& prop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "SyncOneData");

	Params::Global_Voice_C_SyncOneData Parms{};

	Parms.prop = std::move(prop);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Global_Voice.Global_Voice_C.SyncPushOneData
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    prop                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UGlobal_Voice_C::SyncPushOneData(const class FString& prop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "SyncPushOneData");

	Params::Global_Voice_C_SyncPushOneData Parms{};

	Parms.prop = std::move(prop);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Global_Voice.Global_Voice_C.Transitions_Enter
// (Public, BlueprintCallable, BlueprintEvent)

void UGlobal_Voice_C::Transitions_Enter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("Global_Voice_C", "Transitions_Enter");

	UObject::ProcessEvent(Func, nullptr);
}

}

