#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemCategoryStruct

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct ItemCategoryStruct.ItemCategoryStruct
// 0x0020 (0x0020 - 0x0000)
struct FItemCategoryStruct final
{
public:
	int32                                         ItemType_3_66A1B52D404220A2A486229A8411D2AE;       // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ItemSubType_11_67424D2343A5BFA8ED0DA1B1B40EA42C;   // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   ItemCategory_12_B638EF8A4363A06C9A4A38AD33BB41AB;  // 0x0008(0x0018)(Edit, BlueprintVisible)
};

}

