#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LitePC_MainOptionUI

#include "Basic.hpp"


namespace SDK::Params
{

// Function LitePC_MainOptionUI.LitePC_MainOptionUI_C.ExecuteUbergraph_LitePC_MainOptionUI
// 0x00C8 (0x00C8 - 0x0000)
struct LitePC_MainOptionUI_C_ExecuteUbergraph_LitePC_MainOptionUI final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_IsValid_ReturnValue : 1;                  // 0x0010(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AHUD*                                   CallFunc_GetHUD_ReturnValue;                       // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_LitePCLobbyHUD_C*                   K2Node_DynamicCast_AsBP_Lite_PCLobby_HUD;          // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess : 1;                   // 0x0028(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IInterfaceMainOption_C> K2Node_DynamicCast_AsInterface_Main_Option;       // 0x0030(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         K2Node_DynamicCast_bSuccess2 : 1;                  // 0x0040(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0048(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         CallFunc_GetActiveWidgetIndex_ReturnValue;         // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate2;             // 0x0060(0x0010)(ZeroConstructor, NoDestructor)
	class UWidget*                                CallFunc_GetWidgetAtIndex_ReturnValue;             // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTslBaseOptionWidget*                   K2Node_DynamicCast_AsTsl_Base_Option_Widget;       // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess3 : 1;                  // 0x0080(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UOptionButton_C*                        K2Node_DynamicCast_AsOption_Button;                // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess4 : 1;                  // 0x0098(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsEnableApply_ReturnValue : 1;            // 0x0099(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_9A[0x2];                                       // 0x009A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ___int_Variable;                                   // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetNumWidgets_ReturnValue;                // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetWidgetAtIndex_ReturnValue2;            // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTslBaseOptionWidget*                   K2Node_DynamicCast_AsTsl_Base_Option_Widget2;      // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess5 : 1;                  // 0x00C0(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_LessEqual_IntInt_ReturnValue : 1;         // 0x00C1(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_C2[0x2];                                       // 0x00C2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function LitePC_MainOptionUI.LitePC_MainOptionUI_C.ClearOptionButtonsColors
// 0x0028 (0x0028 - 0x0000)
struct LitePC_MainOptionUI_C_ClearOptionButtonsColors final
{
public:
	int32                                         ___int_Variable;                                   // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetChildrenCount_ReturnValue;             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UOptionButton_C*                        K2Node_DynamicCast_AsOption_Button;                // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess : 1;                   // 0x0020(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_LessEqual_IntInt_ReturnValue : 1;         // 0x0021(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_22[0x2];                                       // 0x0022(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function LitePC_MainOptionUI.LitePC_MainOptionUI_C.IsApplyButtonEnabled
// 0x0007 (0x0007 - 0x0000)
struct LitePC_MainOptionUI_C_IsApplyButtonEnabled final
{
public:
	uint8                                         ReturnValue : 1;                                   // 0x0000(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsChanged_ReturnValue : 1;                // 0x0001(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsValid_ReturnValue : 1;                  // 0x0002(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsKeyUp_ReturnValue : 1;                  // 0x0003(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsEnableApply_ReturnValue : 1;            // 0x0004(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_BooleanAND_ReturnValue : 1;               // 0x0005(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_BooleanAND_ReturnValue2 : 1;              // 0x0006(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function LitePC_MainOptionUI.LitePC_MainOptionUI_C.CloseMainOption
// 0x0018 (0x0018 - 0x0000)
struct LitePC_MainOptionUI_C_CloseMainOption final
{
public:
	class ASTExtraPlayerController*               CallFunc_GetOwningPlayer_ReturnValue;              // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_STExtraPlayerControllerPC_C*        K2Node_DynamicCast_AsBP_STExtra_Player_Controller_PC; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess : 1;                   // 0x0010(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function LitePC_MainOptionUI.LitePC_MainOptionUI_C.OnApply
// 0x0001 (0x0001 - 0x0000)
struct LitePC_MainOptionUI_C_OnApply final
{
public:
	uint8                                         CallFunc_IsValid_ReturnValue : 1;                  // 0x0000(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function LitePC_MainOptionUI.LitePC_MainOptionUI_C.ChangeOption
// 0x0020 (0x0020 - 0x0000)
struct LitePC_MainOptionUI_C_ChangeOption final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetWidgetAtIndex_ReturnValue;             // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTslBaseOptionWidget*                   K2Node_DynamicCast_AsTsl_Base_Option_Widget;       // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess : 1;                   // 0x0018(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function LitePC_MainOptionUI.LitePC_MainOptionUI_C.OnDefault
// 0x0001 (0x0001 - 0x0000)
struct LitePC_MainOptionUI_C_OnDefault final
{
public:
	uint8                                         CallFunc_IsValid_ReturnValue : 1;                  // 0x0000(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function LitePC_MainOptionUI.LitePC_MainOptionUI_C.OnReset
// 0x0001 (0x0001 - 0x0000)
struct LitePC_MainOptionUI_C_OnReset final
{
public:
	uint8                                         CallFunc_IsValid_ReturnValue : 1;                  // 0x0000(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function LitePC_MainOptionUI.LitePC_MainOptionUI_C.ShowMessage
// 0x0018 (0x0018 - 0x0000)
struct LitePC_MainOptionUI_C_ShowMessage final
{
public:
	class FText                                   Message;                                           // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};

// Function LitePC_MainOptionUI.LitePC_MainOptionUI_C.Get_OkButton_bIsEnabled_0
// 0x0001 (0x0001 - 0x0000)
struct LitePC_MainOptionUI_C_Get_OkButton_bIsEnabled_0 final
{
public:
	uint8                                         ReturnValue : 1;                                   // 0x0000(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor))
};

// Function LitePC_MainOptionUI.LitePC_MainOptionUI_C.GetResetButton_bIsEnabled_0
// 0x0002 (0x0002 - 0x0000)
struct LitePC_MainOptionUI_C_GetResetButton_bIsEnabled_0 final
{
public:
	uint8                                         ReturnValue : 1;                                   // 0x0000(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_IsChanged_ReturnValue : 1;                // 0x0001(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

}

