#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NewEntireMap

#include "Basic.hpp"

#include "NewEntireMap_classes.hpp"
#include "NewEntireMap_parameters.hpp"


namespace SDK
{

// Function NewEntireMap.NewEntireMap_C.ExecuteUbergraph_NewEntireMap
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::ExecuteUbergraph_NewEntireMap(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "ExecuteUbergraph_NewEntireMap");

	Params::NewEntireMap_C_ExecuteUbergraph_NewEntireMap Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.OnPlayer01MarkerRightClicked
// (BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::OnPlayer01MarkerRightClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "OnPlayer01MarkerRightClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.OnPlayer02MarkerRightClicked
// (BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::OnPlayer02MarkerRightClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "OnPlayer02MarkerRightClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.OnPlayer03MarkerRightClicked
// (BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::OnPlayer03MarkerRightClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "OnPlayer03MarkerRightClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.OnPlayer04MarkerRightClicked
// (BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::OnPlayer04MarkerRightClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "OnPlayer04MarkerRightClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.NullEvent
// (BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::NullEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "NullEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.SetTacticalMarker
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 MousePosition_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 TslMousePosition                                       (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::SetTacticalMarker(const struct FVector2D& MousePosition_0, const struct FVector2D& TslMousePosition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "SetTacticalMarker");

	Params::NewEntireMap_C_SetTacticalMarker Parms{};

	Parms.MousePosition_0 = std::move(MousePosition_0);
	Parms.TslMousePosition = std::move(TslMousePosition);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.UpdateMapColor
// (BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::UpdateMapColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "UpdateMapColor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.OnReleaseMapFocus
// (BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::OnReleaseMapFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "OnReleaseMapFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.OnPressedMapFocus
// (BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::OnPressedMapFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "OnPressedMapFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.OnSpectatorChange
// (BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::OnSpectatorChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "OnSpectatorChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.HideSelfDeadIcon
// (BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::HideSelfDeadIcon_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HideSelfDeadIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.HideDeadIcon
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeammateIndex_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::HideDeadIcon(int32 TeammateIndex_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HideDeadIcon");

	Params::NewEntireMap_C_HideDeadIcon Parms{};

	Parms.TeammateIndex_0 = TeammateIndex_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_36_WheelEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void UNewEntireMap_C::BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_36_WheelEvent__DelegateSignature(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_36_WheelEvent__DelegateSignature");

	Params::NewEntireMap_C_BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_36_WheelEvent__DelegateSignature Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__RestoreHelpButton_K2Node_ComponentBoundEvent_113_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UNewEntireMap_C::BndEvt__RestoreHelpButton_K2Node_ComponentBoundEvent_113_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__RestoreHelpButton_K2Node_ComponentBoundEvent_113_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__MinimizeHelpButton_K2Node_ComponentBoundEvent_54_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UNewEntireMap_C::BndEvt__MinimizeHelpButton_K2Node_ComponentBoundEvent_54_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__MinimizeHelpButton_K2Node_ComponentBoundEvent_54_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.OnCharacterStateChangeDelegate
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ExtraPlayerLiveState                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ACharacter*                       OwnerCharacter                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::OnCharacterStateChangeDelegate(ExtraPlayerLiveState State, class ACharacter* OwnerCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "OnCharacterStateChangeDelegate");

	Params::NewEntireMap_C_OnCharacterStateChangeDelegate Parms{};

	Parms.State = State;
	Parms.OwnerCharacter = OwnerCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.InitMapStandardPoint
// (BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::InitMapStandardPoint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "InitMapStandardPoint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.OnPlayerTeammateStateChange
// (BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::OnPlayerTeammateStateChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "OnPlayerTeammateStateChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_60_OperateBegin__DelegateSignature
// (BlueprintEvent)

void UNewEntireMap_C::BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_60_OperateBegin__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_60_OperateBegin__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_36_OperateEnd__DelegateSignature
// (BlueprintEvent)

void UNewEntireMap_C::BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_36_OperateEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_36_OperateEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__Button_0_K2Node_ComponentBoundEvent_98_OnButtonReleasedEvent__DelegateSignature
// (BlueprintEvent)

void UNewEntireMap_C::BndEvt__Button_0_K2Node_ComponentBoundEvent_98_OnButtonReleasedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__Button_0_K2Node_ComponentBoundEvent_98_OnButtonReleasedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__Button_0_K2Node_ComponentBoundEvent_71_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UNewEntireMap_C::BndEvt__Button_0_K2Node_ComponentBoundEvent_71_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__Button_0_K2Node_ComponentBoundEvent_71_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.ReConnectGameStateInfoNotify
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FReConnectGameStateInfo&   ReConnectInfo                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UNewEntireMap_C::ReConnectGameStateInfoNotify(const struct FReConnectGameStateInfo& ReConnectInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "ReConnectGameStateInfoNotify");

	Params::NewEntireMap_C_ReConnectGameStateInfoNotify Parms{};

	Parms.ReConnectInfo = std::move(ReConnectInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.RedrawMap
// (BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::RedrawMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "RedrawMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.ReceivedInitWidget
// (Event, Public, BlueprintEvent)

void UNewEntireMap_C::ReceivedInitWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "ReceivedInitWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_203_ScaleMap__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   ScaleValue                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_203_ScaleMap__DelegateSignature(float ScaleValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_203_ScaleMap__DelegateSignature");

	Params::NewEntireMap_C_BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_203_ScaleMap__DelegateSignature Parms{};

	Parms.ScaleValue = ScaleValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.InitPlayerState
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::InitPlayerState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "InitPlayerState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__Button_MyMark_K2Node_ComponentBoundEvent_908_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UNewEntireMap_C::BndEvt__Button_MyMark_K2Node_ComponentBoundEvent_908_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__Button_MyMark_K2Node_ComponentBoundEvent_908_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__Button_SelfMark_K2Node_ComponentBoundEvent_491_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UNewEntireMap_C::BndEvt__Button_SelfMark_K2Node_ComponentBoundEvent_491_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__Button_SelfMark_K2Node_ComponentBoundEvent_491_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__Button_DelMarkIcon_K2Node_ComponentBoundEvent_440_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UNewEntireMap_C::BndEvt__Button_DelMarkIcon_K2Node_ComponentBoundEvent_440_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__Button_DelMarkIcon_K2Node_ComponentBoundEvent_440_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__Button_SelfLock_K2Node_ComponentBoundEvent_350_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UNewEntireMap_C::BndEvt__Button_SelfLock_K2Node_ComponentBoundEvent_350_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__Button_SelfLock_K2Node_ComponentBoundEvent_350_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_54_SetMarker__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const struct FVector2D&                 Position                                               (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_54_SetMarker__DelegateSignature(const struct FVector2D& Position)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_54_SetMarker__DelegateSignature");

	Params::NewEntireMap_C_BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_54_SetMarker__DelegateSignature Parms{};

	Parms.Position = std::move(Position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_286_MoveMap__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const struct FVector2D&                 Offset                                                 (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_286_MoveMap__DelegateSignature(const struct FVector2D& Offset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_286_MoveMap__DelegateSignature");

	Params::NewEntireMap_C_BndEvt__MapCircleAndLineBlackboard_K2Node_ComponentBoundEvent_286_MoveMap__DelegateSignature Parms{};

	Parms.Offset = std::move(Offset);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__Slider_MapZoom_K2Node_ComponentBoundEvent_59_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::BndEvt__Slider_MapZoom_K2Node_ComponentBoundEvent_59_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__Slider_MapZoom_K2Node_ComponentBoundEvent_59_OnFloatValueChangedEvent__DelegateSignature");

	Params::NewEntireMap_C_BndEvt__Slider_MapZoom_K2Node_ComponentBoundEvent_59_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__Button_ZoomIn_K2Node_ComponentBoundEvent_52_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UNewEntireMap_C::BndEvt__Button_ZoomIn_K2Node_ComponentBoundEvent_52_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__Button_ZoomIn_K2Node_ComponentBoundEvent_52_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__Button_ZoomOut_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UNewEntireMap_C::BndEvt__Button_ZoomOut_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__Button_ZoomOut_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.ReceiveAirAttackBroadcast
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EAirAttackInfo                          airattacktype                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   waveindex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::ReceiveAirAttackBroadcast(EAirAttackInfo airattacktype, int32 waveindex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "ReceiveAirAttackBroadcast");

	Params::NewEntireMap_C_ReceiveAirAttackBroadcast Parms{};

	Parms.airattacktype = airattacktype;
	Parms.waveindex = waveindex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "Tick");

	Params::NewEntireMap_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.BndEvt__Button_HideMap_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UNewEntireMap_C::BndEvt__Button_HideMap_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BndEvt__Button_HideMap_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// uint8                                   IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UNewEntireMap_C::PreConstruct(uint8 IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "PreConstruct");

	Params::NewEntireMap_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.UpdatePlayerState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ExtraPlayerLiveState                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ACharacter*                       OwnerCharacter                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::UpdatePlayerState(ExtraPlayerLiveState State, class ACharacter* OwnerCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "UpdatePlayerState");

	Params::NewEntireMap_C_UpdatePlayerState Parms{};

	Parms.State = State;
	Parms.OwnerCharacter = OwnerCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.GetMarkerToWorldVector
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector*                         NewParam                                               (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::GetMarkerToWorldVector(struct FVector* NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "GetMarkerToWorldVector");

	Params::NewEntireMap_C_GetMarkerToWorldVector Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = std::move(Parms.NewParam);
}


// Function NewEntireMap.NewEntireMap_C.MapVectorToWorldVector
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 MapVector                                              (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector2D*                       WORLDMAP                                               (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::MapVectorToWorldVector(const struct FVector2D& MapVector, struct FVector2D* WORLDMAP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "MapVectorToWorldVector");

	Params::NewEntireMap_C_MapVectorToWorldVector Parms{};

	Parms.MapVector = std::move(MapVector);

	UObject::ProcessEvent(Func, &Parms);

	if (WORLDMAP != nullptr)
		*WORLDMAP = std::move(Parms.WORLDMAP);
}


// Function NewEntireMap.NewEntireMap_C.HandleAirAttackBroadcast
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EAirAttackInfo                          AttackMsg                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Wave                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::HandleAirAttackBroadcast(EAirAttackInfo AttackMsg, int32 Wave)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HandleAirAttackBroadcast");

	Params::NewEntireMap_C_HandleAirAttackBroadcast Parms{};

	Parms.AttackMsg = AttackMsg;
	Parms.Wave = Wave;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.ChangeMapSize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 Size                                                   (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::ChangeMapSize(const struct FVector2D& Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "ChangeMapSize");

	Params::NewEntireMap_C_ChangeMapSize Parms{};

	Parms.Size = std::move(Size);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.RepositionMarkerAndPin
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::RepositionMarkerAndPin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "RepositionMarkerAndPin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.ChangeMapPivot
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   AligX                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   AligY                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::ChangeMapPivot(float AligX, float AligY)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "ChangeMapPivot");

	Params::NewEntireMap_C_ChangeMapPivot Parms{};

	Parms.AligX = AligX;
	Parms.AligY = AligY;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.HandleMapMove
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 MoveOffset                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::HandleMapMove(const struct FVector2D& MoveOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HandleMapMove");

	Params::NewEntireMap_C_HandleMapMove Parms{};

	Parms.MoveOffset = std::move(MoveOffset);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.GetMapMaxAligByMapSize
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FVector2D&                 MapSize                                                (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  MinAlig                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  MaxAlig                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::GetMapMaxAligByMapSize(const struct FVector2D& MapSize, float* MinAlig, float* MaxAlig)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "GetMapMaxAligByMapSize");

	Params::NewEntireMap_C_GetMapMaxAligByMapSize Parms{};

	Parms.MapSize = std::move(MapSize);

	UObject::ProcessEvent(Func, &Parms);

	if (MinAlig != nullptr)
		*MinAlig = Parms.MinAlig;

	if (MaxAlig != nullptr)
		*MaxAlig = Parms.MaxAlig;
}


// Function NewEntireMap.NewEntireMap_C.ClampAlig
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   MaxAlig                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   MinAlig                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::ClampAlig(float MaxAlig, float MinAlig)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "ClampAlig");

	Params::NewEntireMap_C_ClampAlig Parms{};

	Parms.MaxAlig = MaxAlig;
	Parms.MinAlig = MinAlig;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.GetObjectAligInCurMapSize
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FVector2D&                 Pos                                                    (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  AligX                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  AligY                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::GetObjectAligInCurMapSize(const struct FVector2D& Pos, float* AligX, float* AligY)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "GetObjectAligInCurMapSize");

	Params::NewEntireMap_C_GetObjectAligInCurMapSize Parms{};

	Parms.Pos = std::move(Pos);

	UObject::ProcessEvent(Func, &Parms);

	if (AligX != nullptr)
		*AligX = Parms.AligX;

	if (AligY != nullptr)
		*AligY = Parms.AligY;
}


// Function NewEntireMap.NewEntireMap_C.RepositionSelfMarker
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::RepositionSelfMarker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "RepositionSelfMarker");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.GetSelfImage
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UImage**                          SelfMarker                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::GetSelfImage(class UImage** SelfMarker)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "GetSelfImage");

	Params::NewEntireMap_C_GetSelfImage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SelfMarker != nullptr)
		*SelfMarker = Parms.SelfMarker;
}


// Function NewEntireMap.NewEntireMap_C.GetSelfMarkerGrid
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UCanvasPanel**                    SelfMarker2                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::GetSelfMarkerGrid(class UCanvasPanel** SelfMarker2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "GetSelfMarkerGrid");

	Params::NewEntireMap_C_GetSelfMarkerGrid Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SelfMarker2 != nullptr)
		*SelfMarker2 = Parms.SelfMarker2;
}


// Function NewEntireMap.NewEntireMap_C.InitTeamMateUIArray
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::InitTeamMateUIArray()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "InitTeamMateUIArray");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.SetTeamInfoName
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::SetTeamInfoName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "SetTeamInfoName");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.SetTeamLocAndRot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class ASTExtraPlayerState*>&     Array                                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)

void UNewEntireMap_C::SetTeamLocAndRot(TArray<class ASTExtraPlayerState*>& Array)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "SetTeamLocAndRot");

	Params::NewEntireMap_C_SetTeamLocAndRot Parms{};

	Parms.Array = std::move(Array);

	UObject::ProcessEvent(Func, &Parms);

	Array = std::move(Parms.Array);
}


// Function NewEntireMap.NewEntireMap_C.GetTeamMateBySerialNumber
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   TeammateIndex_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Out                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::GetTeamMateBySerialNumber(int32 TeammateIndex_0, int32* Out)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "GetTeamMateBySerialNumber");

	Params::NewEntireMap_C_GetTeamMateBySerialNumber Parms{};

	Parms.TeammateIndex_0 = TeammateIndex_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Out != nullptr)
		*Out = Parms.Out;
}


// Function NewEntireMap.NewEntireMap_C.SetTeamMateNameInMap
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::SetTeamMateNameInMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "SetTeamMateNameInMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.BindTeamMapMarkDelegate
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::BindTeamMapMarkDelegate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BindTeamMapMarkDelegate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.RepositionMapMark
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ChangeIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::RepositionMapMark(int32 ChangeIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "RepositionMapMark");

	Params::NewEntireMap_C_RepositionMapMark Parms{};

	Parms.ChangeIndex = ChangeIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.GetSelfMarkImageInRight
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UImage**                          NewParam                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::GetSelfMarkImageInRight(class UImage** NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "GetSelfMarkImageInRight");

	Params::NewEntireMap_C_GetSelfMarkImageInRight Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function NewEntireMap.NewEntireMap_C.GetTeamMateListFromPlayerState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class ASTExtraPlayerState*>*     TeammateList                                           (Parm, OutParm, ZeroConstructor)

void UNewEntireMap_C::GetTeamMateListFromPlayerState(TArray<class ASTExtraPlayerState*>* TeammateList)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "GetTeamMateListFromPlayerState");

	Params::NewEntireMap_C_GetTeamMateListFromPlayerState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (TeammateList != nullptr)
		*TeammateList = std::move(Parms.TeammateList);
}


// Function NewEntireMap.NewEntireMap_C.GetPlayerColorByIndex
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor*                    Color                                                  (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::GetPlayerColorByIndex(int32 Index_0, struct FLinearColor* Color)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "GetPlayerColorByIndex");

	Params::NewEntireMap_C_GetPlayerColorByIndex Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Color != nullptr)
		*Color = std::move(Parms.Color);
}


// Function NewEntireMap.NewEntireMap_C.SetPlayerIdxAndColor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   idx                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::SetPlayerIdxAndColor(int32 idx)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "SetPlayerIdxAndColor");

	Params::NewEntireMap_C_SetPlayerIdxAndColor Parms{};

	Parms.idx = idx;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.HandleReconnectInfo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FReConnectGameStateInfo&   ReConnectInfo                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UNewEntireMap_C::HandleReconnectInfo(const struct FReConnectGameStateInfo& ReConnectInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HandleReconnectInfo");

	Params::NewEntireMap_C_HandleReconnectInfo Parms{};

	Parms.ReConnectInfo = std::move(ReConnectInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.SetMateNum
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UImage*                           PlayerImg                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PlayerIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::SetMateNum(class UImage* PlayerImg, int32 PlayerIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "SetMateNum");

	Params::NewEntireMap_C_SetMateNum Parms{};

	Parms.PlayerImg = PlayerImg;
	Parms.PlayerIndex = PlayerIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.SetMateColor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UImage*                           TargetImg                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PlayerIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::SetMateColor(class UImage* TargetImg, int32 PlayerIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "SetMateColor");

	Params::NewEntireMap_C_SetMateColor Parms{};

	Parms.TargetImg = TargetImg;
	Parms.PlayerIndex = PlayerIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.SetMateName
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    PlayerName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UTextBlock*                       LabName                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::SetMateName(const class FString& PlayerName, class UTextBlock* LabName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "SetMateName");

	Params::NewEntireMap_C_SetMateName Parms{};

	Parms.PlayerName = std::move(PlayerName);
	Parms.LabName = LabName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.Reconnect_ResetUIByPlayerControllerState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::Reconnect_ResetUIByPlayerControllerState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "Reconnect_ResetUIByPlayerControllerState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.GMShowMarkerLocation
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::GMShowMarkerLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "GMShowMarkerLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.ShowMarkerLocationText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 Vector                                                 (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::ShowMarkerLocationText(const struct FVector2D& Vector)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "ShowMarkerLocationText");

	Params::NewEntireMap_C_ShowMarkerLocationText Parms{};

	Parms.Vector = std::move(Vector);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.MakeMarker
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 MarkAligment                                           (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::MakeMarker(const struct FVector2D& MarkAligment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "MakeMarker");

	Params::NewEntireMap_C_MakeMarker Parms{};

	Parms.MarkAligment = std::move(MarkAligment);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.SetSelfInfoAndColor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ATslLPCPlayerState*               playState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::SetSelfInfoAndColor(class ATslLPCPlayerState* playState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "SetSelfInfoAndColor");

	Params::NewEntireMap_C_SetSelfInfoAndColor Parms{};

	Parms.playState = playState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.RefreshTeammateIcon
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::RefreshTeammateIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "RefreshTeammateIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.ShowMarkerDistance
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::ShowMarkerDistance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "ShowMarkerDistance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.CaclMarkDir
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 MarkPoint                                              (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Distance                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::CaclMarkDir(const struct FVector2D& MarkPoint, int32* Distance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "CaclMarkDir");

	Params::NewEntireMap_C_CaclMarkDir Parms{};

	Parms.MarkPoint = std::move(MarkPoint);

	UObject::ProcessEvent(Func, &Parms);

	if (Distance != nullptr)
		*Distance = Parms.Distance;
}


// Function NewEntireMap.NewEntireMap_C.MarkPoint2RealLocation
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 InVec                                                  (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector2D                        ReturnValue                                            (Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector2D UNewEntireMap_C::MarkPoint2RealLocation(const struct FVector2D& InVec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "MarkPoint2RealLocation");

	Params::NewEntireMap_C_MarkPoint2RealLocation Parms{};

	Parms.InVec = std::move(InVec);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function NewEntireMap.NewEntireMap_C.ShowFriendsDistance
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::ShowFriendsDistance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "ShowFriendsDistance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.UpdateAirplaneRoute
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Stop                                                   (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   IsDraw                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UNewEntireMap_C::UpdateAirplaneRoute(const struct FVector& Start, const struct FVector& Stop, uint8 IsDraw)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "UpdateAirplaneRoute");

	Params::NewEntireMap_C_UpdateAirplaneRoute Parms{};

	Parms.Start = std::move(Start);
	Parms.Stop = std::move(Stop);
	Parms.IsDraw = IsDraw;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.UpdateLastDriveVehicleIcon
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::UpdateLastDriveVehicleIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "UpdateLastDriveVehicleIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.HideSelfDeadIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   bIsShow                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UNewEntireMap_C::HideSelfDeadIcon(uint8 bIsShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HideSelfDeadIcon");

	Params::NewEntireMap_C_HideSelfDeadIcon Parms{};

	Parms.bIsShow = bIsShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.HideTeammateDeadIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeammateIndex_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   bIsShow                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UNewEntireMap_C::HideTeammateDeadIcon(int32 TeammateIndex_0, uint8 bIsShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HideTeammateDeadIcon");

	Params::NewEntireMap_C_HideTeammateDeadIcon Parms{};

	Parms.TeammateIndex_0 = TeammateIndex_0;
	Parms.bIsShow = bIsShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.OnCharacterStateChange
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            Teammate                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ExtraPlayerLiveState                    LiveState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::OnCharacterStateChange(class APawn* Teammate, ExtraPlayerLiveState LiveState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "OnCharacterStateChange");

	Params::NewEntireMap_C_OnCharacterStateChange Parms{};

	Parms.Teammate = Teammate;
	Parms.LiveState = LiveState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.ClearAllMark
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::ClearAllMark()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "ClearAllMark");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.On_Button_Player01MarkInMap_MouseButtonDown_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FPointerEvent&                   MouseEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UNewEntireMap_C::On_Button_Player01MarkInMap_MouseButtonDown_0(const struct FGeometry& MyGeometry, struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "On_Button_Player01MarkInMap_MouseButtonDown_0");

	Params::NewEntireMap_C_On_Button_Player01MarkInMap_MouseButtonDown_0 Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	MouseEvent = std::move(Parms.MouseEvent);

	return Parms.ReturnValue;
}


// Function NewEntireMap.NewEntireMap_C.HideMarker
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::HideMarker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HideMarker");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.IsLocalPlayerIndex
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   InIndex                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8*                                  Ret                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UNewEntireMap_C::IsLocalPlayerIndex(int32 InIndex, uint8* Ret)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "IsLocalPlayerIndex");

	Params::NewEntireMap_C_IsLocalPlayerIndex Parms{};

	Parms.InIndex = InIndex;

	UObject::ProcessEvent(Func, &Parms);

	if (Ret != nullptr)
		*Ret = Parms.Ret;
}


// Function NewEntireMap.NewEntireMap_C.SetMarkerAtCurrentPosition
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::SetMarkerAtCurrentPosition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "SetMarkerAtCurrentPosition");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.MoveToSelfPosition
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::MoveToSelfPosition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "MoveToSelfPosition");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.SetMapCenterPos
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::SetMapCenterPos()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "SetMapCenterPos");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.WheelEvent
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void UNewEntireMap_C::WheelEvent(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "WheelEvent");

	Params::NewEntireMap_C_WheelEvent Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.MapInfoUpdate
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::MapInfoUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "MapInfoUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.HandleLastCircle
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   LastCircle                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::HandleLastCircle(const struct FVector& LastCircle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HandleLastCircle");

	Params::NewEntireMap_C_HandleLastCircle Parms{};

	Parms.LastCircle = std::move(LastCircle);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.UpdateLastCircle
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::UpdateLastCircle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "UpdateLastCircle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.TickCircle
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::TickCircle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "TickCircle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.HidePlayerInfoCanvasByIndex
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   IsShow                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::HidePlayerInfoCanvasByIndex(uint8 IsShow, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HidePlayerInfoCanvasByIndex");

	Params::NewEntireMap_C_HidePlayerInfoCanvasByIndex Parms{};

	Parms.IsShow = IsShow;
	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.HideSelfInfoCanvas
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   IsShow                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UNewEntireMap_C::HideSelfInfoCanvas(uint8 IsShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HideSelfInfoCanvas");

	Params::NewEntireMap_C_HideSelfInfoCanvas Parms{};

	Parms.IsShow = IsShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.HidePlaneImage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   IsShow                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UNewEntireMap_C::HidePlaneImage(uint8 IsShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HidePlaneImage");

	Params::NewEntireMap_C_HidePlaneImage Parms{};

	Parms.IsShow = IsShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.ReCalMapInfo
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FMapRealTimeInfo*                RealTimeInfo                                           (Parm, OutParm, NoDestructor)

void UNewEntireMap_C::ReCalMapInfo(struct FMapRealTimeInfo* RealTimeInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "ReCalMapInfo");

	Params::NewEntireMap_C_ReCalMapInfo Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (RealTimeInfo != nullptr)
		*RealTimeInfo = std::move(Parms.RealTimeInfo);
}


// Function NewEntireMap.NewEntireMap_C.ShowAirplane
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::ShowAirplane()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "ShowAirplane");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.HideAirplane
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::HideAirplane()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HideAirplane");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.SetKeyFocus
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::SetKeyFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "SetKeyFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.RemoveKeyFocus
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::RemoveKeyFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "RemoveKeyFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.InterpolateZoomInOut
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InterpSpeed                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::InterpolateZoomInOut(const struct FGeometry& MyGeometry, float InDeltaTime, float InterpSpeed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "InterpolateZoomInOut");

	Params::NewEntireMap_C_InterpolateZoomInOut Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;
	Parms.InterpSpeed = InterpSpeed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.GetMapCenter
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   InAligX                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InAligY                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  OutAligX                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  OutAligY                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::GetMapCenter(float InAligX, float InAligY, float* OutAligX, float* OutAligY)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "GetMapCenter");

	Params::NewEntireMap_C_GetMapCenter Parms{};

	Parms.InAligX = InAligX;
	Parms.InAligY = InAligY;

	UObject::ProcessEvent(Func, &Parms);

	if (OutAligX != nullptr)
		*OutAligX = Parms.OutAligX;

	if (OutAligY != nullptr)
		*OutAligY = Parms.OutAligY;
}


// Function NewEntireMap.NewEntireMap_C.IsMouseInMarker
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FVector2D&                 InMousePos                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8*                                  bInMarker                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UNewEntireMap_C::IsMouseInMarker(const struct FVector2D& InMousePos, uint8* bInMarker)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "IsMouseInMarker");

	Params::NewEntireMap_C_IsMouseInMarker Parms{};

	Parms.InMousePos = std::move(InMousePos);

	UObject::ProcessEvent(Func, &Parms);

	if (bInMarker != nullptr)
		*bInMarker = Parms.bInMarker;
}


// Function NewEntireMap.NewEntireMap_C.HideTeammateIcon
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeammateIndex_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   bIsShow                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// TArray<class UWidget*>&                 IconArray                                              (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)

void UNewEntireMap_C::HideTeammateIcon(int32 TeammateIndex_0, uint8 bIsShow, TArray<class UWidget*>& IconArray)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HideTeammateIcon");

	Params::NewEntireMap_C_HideTeammateIcon Parms{};

	Parms.TeammateIndex_0 = TeammateIndex_0;
	Parms.bIsShow = bIsShow;
	Parms.IconArray = std::move(IconArray);

	UObject::ProcessEvent(Func, &Parms);

	IconArray = std::move(Parms.IconArray);
}


// Function NewEntireMap.NewEntireMap_C.ResetSelfMarker
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::ResetSelfMarker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "ResetSelfMarker");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.BlockInputWhileTacticalWidgetShow
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::BlockInputWhileTacticalWidgetShow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "BlockInputWhileTacticalWidgetShow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.UnblockInputAfterTacticalWidgetHide
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::UnblockInputAfterTacticalWidgetHide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "UnblockInputAfterTacticalWidgetHide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.HideUIOnObserver
// (Public, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::HideUIOnObserver()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "HideUIOnObserver");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.SetWorldMapTexture
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMiniMapStandardPoint*            MapInfoObj                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewEntireMap_C::SetWorldMapTexture(class AMiniMapStandardPoint* MapInfoObj)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "SetWorldMapTexture");

	Params::NewEntireMap_C_SetWorldMapTexture Parms{};

	Parms.MapInfoObj = MapInfoObj;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewEntireMap.NewEntireMap_C.CheckMapInitSize
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewEntireMap_C::CheckMapInitSize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "CheckMapInitSize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewEntireMap.NewEntireMap_C.OnPaint
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// struct FPaintContext&                   Context                                                (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UNewEntireMap_C::OnPaint(struct FPaintContext& Context) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewEntireMap_C", "OnPaint");

	Params::NewEntireMap_C_OnPaint Parms{};

	Parms.Context = std::move(Context);

	UObject::ProcessEvent(Func, &Parms);

	Context = std::move(Parms.Context);
}

}

