#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NewMiniMap

#include "Basic.hpp"

#include "NewMiniMap_classes.hpp"
#include "NewMiniMap_parameters.hpp"


namespace SDK
{

// Function NewMiniMap.NewMiniMap_C.ExecuteUbergraph_NewMiniMap
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::ExecuteUbergraph_NewMiniMap(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "ExecuteUbergraph_NewMiniMap");

	Params::NewMiniMap_C_ExecuteUbergraph_NewMiniMap Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.HideSelfDeadIcon
// (BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::HideSelfDeadIcon_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "HideSelfDeadIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.HideDeadIcon
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeammateIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::HideDeadIcon(int32 TeammateIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "HideDeadIcon");

	Params::NewMiniMap_C_HideDeadIcon Parms{};

	Parms.TeammateIndex = TeammateIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.MapResize
// (BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::MapResize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "MapResize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.OnCharacterStateChangeDelegate
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ExtraPlayerLiveState                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ACharacter*                       OwnerCharacter                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::OnCharacterStateChangeDelegate(ExtraPlayerLiveState State, class ACharacter* OwnerCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "OnCharacterStateChangeDelegate");

	Params::NewMiniMap_C_OnCharacterStateChangeDelegate Parms{};

	Parms.State = State;
	Parms.OwnerCharacter = OwnerCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.OnTeamMateChange
// (BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::OnTeamMateChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "OnTeamMateChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.InitMapStandardPoint
// (BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::InitMapStandardPoint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "InitMapStandardPoint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.PlayerEnterFighting
// (BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::PlayerEnterFighting()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "PlayerEnterFighting");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.OnSpectatorChangeEvent
// (BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::OnSpectatorChangeEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "OnSpectatorChangeEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.PlayerEnterFlying
// (BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::PlayerEnterFlying()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "PlayerEnterFlying");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.ReConnectGameStateInfoNotify
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FReConnectGameStateInfo&   ReConnectInfo                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UNewMiniMap_C::ReConnectGameStateInfoNotify(const struct FReConnectGameStateInfo& ReConnectInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "ReConnectGameStateInfoNotify");

	Params::NewMiniMap_C_ReConnectGameStateInfoNotify Parms{};

	Parms.ReConnectInfo = std::move(ReConnectInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UNewMiniMap_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.ReceivedInitWidget
// (Event, Public, BlueprintEvent)

void UNewMiniMap_C::ReceivedInitWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "ReceivedInitWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.InitPlayerState
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::InitPlayerState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "InitPlayerState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.ReceiveAirAttackBroadcast
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EAirAttackInfo                          airattacktype                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   waveindex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::ReceiveAirAttackBroadcast(EAirAttackInfo airattacktype, int32 waveindex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "ReceiveAirAttackBroadcast");

	Params::NewMiniMap_C_ReceiveAirAttackBroadcast Parms{};

	Parms.airattacktype = airattacktype;
	Parms.waveindex = waveindex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.HideEntireMap
// (BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::HideEntireMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "HideEntireMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "Tick");

	Params::NewMiniMap_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// uint8                                   IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UNewMiniMap_C::PreConstruct(uint8 IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "PreConstruct");

	Params::NewMiniMap_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.UpdatePlayerState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ExtraPlayerLiveState                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ACharacter*                       OwnerCharacter                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::UpdatePlayerState(ExtraPlayerLiveState State, class ACharacter* OwnerCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "UpdatePlayerState");

	Params::NewMiniMap_C_UpdatePlayerState Parms{};

	Parms.State = State;
	Parms.OwnerCharacter = OwnerCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.SetPlayerMarkerRotation
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::SetPlayerMarkerRotation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "SetPlayerMarkerRotation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.HandleAirAttackBroadcast
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EAirAttackInfo                          AttackMsg                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Wave                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::HandleAirAttackBroadcast(EAirAttackInfo AttackMsg, int32 Wave)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "HandleAirAttackBroadcast");

	Params::NewMiniMap_C_HandleAirAttackBroadcast Parms{};

	Parms.AttackMsg = AttackMsg;
	Parms.Wave = Wave;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.LoadMapByLevelName
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::LoadMapByLevelName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "LoadMapByLevelName");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.BindTeamMapMarkDelegate
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::BindTeamMapMarkDelegate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "BindTeamMapMarkDelegate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.RepositionMapMark
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::RepositionMapMark(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "RepositionMapMark");

	Params::NewMiniMap_C_RepositionMapMark Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.InitUIWidget
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::InitUIWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "InitUIWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.ShowTeamMateInfoGrid
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class ASTExtraPlayerState*>&     TargetArray                                            (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)

void UNewMiniMap_C::ShowTeamMateInfoGrid(TArray<class ASTExtraPlayerState*>& TargetArray)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "ShowTeamMateInfoGrid");

	Params::NewMiniMap_C_ShowTeamMateInfoGrid Parms{};

	Parms.TargetArray = std::move(TargetArray);

	UObject::ProcessEvent(Func, &Parms);

	TargetArray = std::move(Parms.TargetArray);
}


// Function NewMiniMap.NewMiniMap_C.GetTeamMateListFromPlayerState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// uint8                                   ExcludeSelf                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// TArray<class ASTExtraPlayerState*>*     TeammateList                                           (Parm, OutParm, ZeroConstructor)

void UNewMiniMap_C::GetTeamMateListFromPlayerState(uint8 ExcludeSelf, TArray<class ASTExtraPlayerState*>* TeammateList)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "GetTeamMateListFromPlayerState");

	Params::NewMiniMap_C_GetTeamMateListFromPlayerState Parms{};

	Parms.ExcludeSelf = ExcludeSelf;

	UObject::ProcessEvent(Func, &Parms);

	if (TeammateList != nullptr)
		*TeammateList = std::move(Parms.TeammateList);
}


// Function NewMiniMap.NewMiniMap_C.HideEnterMap
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::HideEnterMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "HideEnterMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.ShowEnterMap
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::ShowEnterMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "ShowEnterMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.HandleReconnectInfo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FReConnectGameStateInfo&   Info                                                   (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UNewMiniMap_C::HandleReconnectInfo(const struct FReConnectGameStateInfo& Info)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "HandleReconnectInfo");

	Params::NewMiniMap_C_HandleReconnectInfo Parms{};

	Parms.Info = std::move(Info);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.ShowMateNum
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::ShowMateNum()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "ShowMateNum");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.SetMateNum
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UImage*                           NumImg                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PlayerIdx                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::SetMateNum(class UImage* NumImg, int32 PlayerIdx)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "SetMateNum");

	Params::NewMiniMap_C_SetMateNum Parms{};

	Parms.NumImg = NumImg;
	Parms.PlayerIdx = PlayerIdx;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.SetMateColor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   PlayerIdx                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UImage*                           TargetImage                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::SetMateColor(int32 PlayerIdx, class UImage* TargetImage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "SetMateColor");

	Params::NewMiniMap_C_SetMateColor Parms{};

	Parms.PlayerIdx = PlayerIdx;
	Parms.TargetImage = TargetImage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.Reconnect_ResetUIByPlayerControllerState
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::Reconnect_ResetUIByPlayerControllerState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "Reconnect_ResetUIByPlayerControllerState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.RedrawSelfMark
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::RedrawSelfMark()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "RedrawSelfMark");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.MiniMapAdjustLimtChange
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::MiniMapAdjustLimtChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "MiniMapAdjustLimtChange");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.ClearAllMark
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::ClearAllMark()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "ClearAllMark");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.SetSelfInfoAndColor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASTExtraPlayerState*              PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::SetSelfInfoAndColor(class ASTExtraPlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "SetSelfInfoAndColor");

	Params::NewMiniMap_C_SetSelfInfoAndColor Parms{};

	Parms.PlayerState = PlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.RefreshTeammateIcon
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::RefreshTeammateIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "RefreshTeammateIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.OnSpectatorChanged
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::OnSpectatorChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "OnSpectatorChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.RefreshLocalPlayer
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::RefreshLocalPlayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "RefreshLocalPlayer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.SetSpectatorInfoAndColor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASTExtraPlayerState*              PS                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::SetSpectatorInfoAndColor(class ASTExtraPlayerState* PS)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "SetSpectatorInfoAndColor");

	Params::NewMiniMap_C_SetSpectatorInfoAndColor Parms{};

	Parms.PS = PS;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.UpdateAirplaneRoute
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   StartLoc                                               (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   EndLoc                                                 (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   IsDraw                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UNewMiniMap_C::UpdateAirplaneRoute(const struct FVector& StartLoc, const struct FVector& EndLoc, uint8 IsDraw)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "UpdateAirplaneRoute");

	Params::NewMiniMap_C_UpdateAirplaneRoute Parms{};

	Parms.StartLoc = std::move(StartLoc);
	Parms.EndLoc = std::move(EndLoc);
	Parms.IsDraw = IsDraw;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.UpdateLastDriveVehicle
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::UpdateLastDriveVehicle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "UpdateLastDriveVehicle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.HandleTeammateOutOfRange
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<int32>&                          InputPin                                               (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)

void UNewMiniMap_C::HandleTeammateOutOfRange(TArray<int32>& InputPin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "HandleTeammateOutOfRange");

	Params::NewMiniMap_C_HandleTeammateOutOfRange Parms{};

	Parms.InputPin = std::move(InputPin);

	UObject::ProcessEvent(Func, &Parms);

	InputPin = std::move(Parms.InputPin);
}


// Function NewMiniMap.NewMiniMap_C.HideSelfDeadIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   bIsShow                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UNewMiniMap_C::HideSelfDeadIcon(uint8 bIsShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "HideSelfDeadIcon");

	Params::NewMiniMap_C_HideSelfDeadIcon Parms{};

	Parms.bIsShow = bIsShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.HideTeammateDeadIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeammateIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   bIsShow                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   PlayerId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::HideTeammateDeadIcon(int32 TeammateIndex, uint8 bIsShow, int32 PlayerId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "HideTeammateDeadIcon");

	Params::NewMiniMap_C_HideTeammateDeadIcon Parms{};

	Parms.TeammateIndex = TeammateIndex;
	Parms.bIsShow = bIsShow;
	Parms.PlayerId = PlayerId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.OnCharacterStateChange
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            self2                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ExtraPlayerLiveState                    InputPin                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::OnCharacterStateChange(class APawn* self2, ExtraPlayerLiveState InputPin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "OnCharacterStateChange");

	Params::NewMiniMap_C_OnCharacterStateChange Parms{};

	Parms.self2 = self2;
	Parms.InputPin = InputPin;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.HandleLastCircle
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   LastCircle                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::HandleLastCircle(const struct FVector& LastCircle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "HandleLastCircle");

	Params::NewMiniMap_C_HandleLastCircle Parms{};

	Parms.LastCircle = std::move(LastCircle);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.TickDynamicScale
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSec                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::TickDynamicScale(float DeltaSec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "TickDynamicScale");

	Params::NewMiniMap_C_TickDynamicScale Parms{};

	Parms.DeltaSec = DeltaSec;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.LerpDynamicScale
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSec                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::LerpDynamicScale(float DeltaSec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "LerpDynamicScale");

	Params::NewMiniMap_C_LerpDynamicScale Parms{};

	Parms.DeltaSec = DeltaSec;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.ReadDynamicScaleTable
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::ReadDynamicScaleTable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "ReadDynamicScaleTable");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.FindScaleFactorByVelocity
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Velocity                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  ScaleFactor                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::FindScaleFactorByVelocity(float Velocity, float* ScaleFactor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "FindScaleFactorByVelocity");

	Params::NewMiniMap_C_FindScaleFactorByVelocity Parms{};

	Parms.Velocity = Velocity;

	UObject::ProcessEvent(Func, &Parms);

	if (ScaleFactor != nullptr)
		*ScaleFactor = Parms.ScaleFactor;
}


// Function NewMiniMap.NewMiniMap_C.ChangeDynamicScale
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   NewScale                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::ChangeDynamicScale(float NewScale)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "ChangeDynamicScale");

	Params::NewMiniMap_C_ChangeDynamicScale Parms{};

	Parms.NewScale = NewScale;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.RepositionItemOnMap
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::RepositionItemOnMap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "RepositionItemOnMap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.Get4*4Scale
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  MiniMapShow4_4Scale                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::Get4_4Scale(float* MiniMapShow4_4Scale)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "Get4*4Scale");

	Params::NewMiniMap_C_Get4_4Scale Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (MiniMapShow4_4Scale != nullptr)
		*MiniMapShow4_4Scale = Parms.MiniMapShow4_4Scale;
}


// Function NewMiniMap.NewMiniMap_C.RedrawAllMapMark
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::RedrawAllMapMark()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "RedrawAllMapMark");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.RedrawAirAttackArea
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::RedrawAirAttackArea()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "RedrawAirAttackArea");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.TickCircle
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::TickCircle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "TickCircle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.HideAirplaneImage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   IsShow                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UNewMiniMap_C::HideAirplaneImage(uint8 IsShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "HideAirplaneImage");

	Params::NewMiniMap_C_HideAirplaneImage Parms{};

	Parms.IsShow = IsShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.HidePlayerInfoCanvasByIndex
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   IsShow                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::HidePlayerInfoCanvasByIndex(uint8 IsShow, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "HidePlayerInfoCanvasByIndex");

	Params::NewMiniMap_C_HidePlayerInfoCanvasByIndex Parms{};

	Parms.IsShow = IsShow;
	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.HideSelfInfoCanvas
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   IsShow                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UNewMiniMap_C::HideSelfInfoCanvas(uint8 IsShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "HideSelfInfoCanvas");

	Params::NewMiniMap_C_HideSelfInfoCanvas Parms{};

	Parms.IsShow = IsShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.ReCalMapInfo
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FMapRealTimeInfo*                Result                                                 (Parm, OutParm, NoDestructor)

void UNewMiniMap_C::ReCalMapInfo(struct FMapRealTimeInfo* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "ReCalMapInfo");

	Params::NewMiniMap_C_ReCalMapInfo Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = std::move(Parms.Result);
}


// Function NewMiniMap.NewMiniMap_C.ResetDeadIcon
// (Public, BlueprintCallable, BlueprintEvent)

void UNewMiniMap_C::ResetDeadIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "ResetDeadIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewMiniMap.NewMiniMap_C.HideTeammateIcon
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeammateIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// uint8                                   bIsShow                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// TArray<class UWidget*>&                 IconArray                                              (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)

void UNewMiniMap_C::HideTeammateIcon(int32 TeammateIndex, uint8 bIsShow, TArray<class UWidget*>& IconArray)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "HideTeammateIcon");

	Params::NewMiniMap_C_HideTeammateIcon Parms{};

	Parms.TeammateIndex = TeammateIndex;
	Parms.bIsShow = bIsShow;
	Parms.IconArray = std::move(IconArray);

	UObject::ProcessEvent(Func, &Parms);

	IconArray = std::move(Parms.IconArray);
}


// Function NewMiniMap.NewMiniMap_C.SetMinimapTexture
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMiniMapStandardPoint*            MapInfoObj                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::SetMinimapTexture(class AMiniMapStandardPoint* MapInfoObj)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "SetMinimapTexture");

	Params::NewMiniMap_C_SetMinimapTexture Parms{};

	Parms.MapInfoObj = MapInfoObj;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewMiniMap.NewMiniMap_C.OnPaint
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// struct FPaintContext&                   Context                                                (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UNewMiniMap_C::OnPaint(struct FPaintContext& Context) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "OnPaint");

	Params::NewMiniMap_C_OnPaint Parms{};

	Parms.Context = std::move(Context);

	UObject::ProcessEvent(Func, &Parms);

	Context = std::move(Parms.Context);
}


// Function NewMiniMap.NewMiniMap_C.GetPlayerColorByIndex
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor*                    Color                                                  (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewMiniMap_C::GetPlayerColorByIndex(int32 Index_0, struct FLinearColor* Color) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("NewMiniMap_C", "GetPlayerColorByIndex");

	Params::NewMiniMap_C_GetPlayerColorByIndex Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Color != nullptr)
		*Color = std::move(Parms.Color);
}

}

