#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OB_CircleChasingProgress_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ShadowTrackerExtra_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass OB_CircleChasingProgress_BP.OB_CircleChasingProgress_BP_C
// 0x0248 (0x0570 - 0x0328)
class UOB_CircleChasingProgress_BP_C final : public UChasingBar
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(Transient, DuplicateTransient)
	class UWidgetAnimation*                       BlueCircleRunning;                                 // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       CleaningProgressBar;                               // 0x0338(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 CautionIcon;                                       // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             CountDownText;                                     // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 PlayerIcon;                                        // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProgressBar*                           ProgressBar_BlueBar;                               // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_Dist;                                    // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_RingNum;                                 // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_Time;                                    // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ASTExtraGameStateBase*                  STExtraGameState;                                  // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CautionFlashing;                                   // 0x0380(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_384[0x4];                                      // 0x0384(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            Taopao_zhongdu_R;                                  // 0x0388(0x0078)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            Taopao_zhongdu_W;                                  // 0x0400(0x0078)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            Taopao_zhongduTips_R;                              // 0x0478(0x0078)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateBrush                            Taopao_zhongduTips_W;                              // 0x04F0(0x0078)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         PlayerEscapProgressMax;                            // 0x0568(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         IsRefreshCircleDistance : 1;                       // 0x056C(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor))

public:
	void ExecuteUbergraph_OB_CircleChasingProgress_BP(int32 EntryPoint);
	void DelayReconverBlueProgressAgain();
	void ReceivedInitWidget();
	void CleanTheProgressBar();
	void OnPlayerEnterExitBlueCircle();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void UpdateCountDownText();
	void OnCountDownTextInvisible();
	void RefreshPlayerEscapePercent();
	void RefreshCircleDistance();
	void RecoverBlueCircleRunProgress();
	void OnWhiteCircleAppearHandle(float BlueCircleMovingCountDownDuration_0);
	void OnBlueCircleRunHandle(float BlueCircleRunDuration_0);
	void RefreshWorldTime();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("OB_CircleChasingProgress_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OB_CircleChasingProgress_BP_C")
	}
	static class UOB_CircleChasingProgress_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOB_CircleChasingProgress_BP_C>();
	}
};

}

