#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PickUpItem_BP

#include "Basic.hpp"

#include "PickUpItem_BP_classes.hpp"
#include "PickUpItem_BP_parameters.hpp"


namespace SDK
{

// Function PickUpItem_BP.PickUpItem_BP_C.ExecuteUbergraph_PickUpItem_BP
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPickUpItem_BP_C::ExecuteUbergraph_PickUpItem_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("PickUpItem_BP_C", "ExecuteUbergraph_PickUpItem_BP");

	Params::PickUpItem_BP_C_ExecuteUbergraph_PickUpItem_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickUpItem_BP.PickUpItem_BP_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UPickUpItem_BP_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("PickUpItem_BP_C", "OnMouseLeave");

	Params::PickUpItem_BP_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickUpItem_BP.PickUpItem_BP_C.BndEvt__Button_ClickItem_K2Node_ComponentBoundEvent_45_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UPickUpItem_BP_C::BndEvt__Button_ClickItem_K2Node_ComponentBoundEvent_45_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("PickUpItem_BP_C", "BndEvt__Button_ClickItem_K2Node_ComponentBoundEvent_45_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PickUpItem_BP.PickUpItem_BP_C.OnTouchEnded
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FPointerEvent&                   InTouchEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UPickUpItem_BP_C::OnTouchEnded(const struct FGeometry& MyGeometry, struct FPointerEvent& InTouchEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("PickUpItem_BP_C", "OnTouchEnded");

	Params::PickUpItem_BP_C_OnTouchEnded Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InTouchEvent = std::move(InTouchEvent);

	UObject::ProcessEvent(Func, &Parms);

	InTouchEvent = std::move(Parms.InTouchEvent);

	return Parms.ReturnValue;
}


// Function PickUpItem_BP.PickUpItem_BP_C.OnTouchStarted
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FPointerEvent&                   InTouchEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UPickUpItem_BP_C::OnTouchStarted(const struct FGeometry& MyGeometry, struct FPointerEvent& InTouchEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("PickUpItem_BP_C", "OnTouchStarted");

	Params::PickUpItem_BP_C_OnTouchStarted Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InTouchEvent = std::move(InTouchEvent);

	UObject::ProcessEvent(Func, &Parms);

	InTouchEvent = std::move(Parms.InTouchEvent);

	return Parms.ReturnValue;
}


// Function PickUpItem_BP.PickUpItem_BP_C.HandlePickup
// (Public, BlueprintCallable, BlueprintEvent)

void UPickUpItem_BP_C::HandlePickup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("PickUpItem_BP_C", "HandlePickup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PickUpItem_BP.PickUpItem_BP_C.OnTouchGesture
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FPointerEvent&                   GestureEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UPickUpItem_BP_C::OnTouchGesture(const struct FGeometry& MyGeometry, struct FPointerEvent& GestureEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("PickUpItem_BP_C", "OnTouchGesture");

	Params::PickUpItem_BP_C_OnTouchGesture Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.GestureEvent = std::move(GestureEvent);

	UObject::ProcessEvent(Func, &Parms);

	GestureEvent = std::move(Parms.GestureEvent);

	return Parms.ReturnValue;
}


// Function PickUpItem_BP.PickUpItem_BP_C.UpdateItemDataByWrap
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FBattleSearchBoxSortingInfo&Info                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UPickUpItem_BP_C::UpdateItemDataByWrap(const struct FBattleSearchBoxSortingInfo& Info)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("PickUpItem_BP_C", "UpdateItemDataByWrap");

	Params::PickUpItem_BP_C_UpdateItemDataByWrap Parms{};

	Parms.Info = std::move(Info);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickUpItem_BP.PickUpItem_BP_C.GetUseless
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8*                                  useless                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPickUpItem_BP_C::GetUseless(uint8* useless)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("PickUpItem_BP_C", "GetUseless");

	Params::PickUpItem_BP_C_GetUseless Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (useless != nullptr)
		*useless = Parms.useless;
}


// Function PickUpItem_BP.PickUpItem_BP_C.UpdateUseless
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   useful_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPickUpItem_BP_C::UpdateUseless(uint8 useful_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("PickUpItem_BP_C", "UpdateUseless");

	Params::PickUpItem_BP_C_UpdateUseless Parms{};

	Parms.useful_0 = useful_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickUpItem_BP.PickUpItem_BP_C.ShowDurable
// (Public, BlueprintCallable, BlueprintEvent)

void UPickUpItem_BP_C::ShowDurable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("PickUpItem_BP_C", "ShowDurable");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PickUpItem_BP.PickUpItem_BP_C.RefreshIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Icon                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPickUpItem_BP_C::RefreshIcon(class UObject* Icon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("PickUpItem_BP_C", "RefreshIcon");

	Params::PickUpItem_BP_C_RefreshIcon Parms{};

	Parms.Icon = Icon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickUpItem_BP.PickUpItem_BP_C.UpdateItemData
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FBattleSearchItemSortingInfo&ItemData                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UPickUpItem_BP_C::UpdateItemData(const struct FBattleSearchItemSortingInfo& ItemData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = GetClass()->GetFunction("PickUpItem_BP_C", "UpdateItemData");

	Params::PickUpItem_BP_C_UpdateItemData Parms{};

	Parms.ItemData = std::move(ItemData);

	UObject::ProcessEvent(Func, &Parms);
}

}

