#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PistolInfoItem_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "BP_STRUCT_Item_type_structs.hpp"
#include "Basic_structs.hpp"
#include "ShadowTrackerExtra_structs.hpp"
#include "UnrealArchExt_classes.hpp"
#include "EBackPackDragOrigin_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PistolInfoItem_BP.PistolInfoItem_BP_C
// 0x0500 (0x07B8 - 0x02B8)
class UPistolInfoItem_BP_C final : public UUAEUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(Transient, DuplicateTransient)
	class UHorizontalBox*                         BulletBox;                                         // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFitingSlotItem_BP_C*                   GripSlot;                                          // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_0;                                   // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_3;                                           // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_4;                                           // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_PistolIcon;                                  // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_SelectedStatus;                              // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_SelectHover;                                 // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ItemContent2;                                      // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ItemContent3;                                      // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFitingSlotItem_BP_C*                   MagazineSlot;                                      // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFitingSlotItem_BP_C*                   MuzzleSlot;                                        // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Pisol_UsingTips;                                   // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFitingSlotItem_BP_C*                   ScopeSlot;                                         // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFitingSlotItem_BP_C*                   StockSlot;                                         // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_0;                                       // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_3;                                       // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_BulletName;                              // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_CurrentNumberOfBullets;                  // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_MaxNumberOfBullets;                      // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_WeaponName;                              // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint8                                         bHasTipsShow : 1;                                  // 0x0370(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor))
	uint8                                         Pad_371[0x7];                                      // 0x0371(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            ParentUserWidget;                                  // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBP_STRUCT_Item_type                   WeaponDataRow;                                     // 0x0380(0x0240)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	struct FSlateBrush                            SmallIconBrush;                                    // 0x05C0(0x0078)(Edit, BlueprintVisible, DisableEditOnInstance)
	uint8                                         bHasStartedTouchIn : 1;                            // 0x0638(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor))
	uint8                                         Pad_639[0x7];                                      // 0x0639(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	UMulticastDelegateProperty_                   ItemBeDragBegin;                                   // 0x0640(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	UMulticastDelegateProperty_                   ItemBeDragCancelled;                               // 0x0650(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FBattleItemData                        battleData;                                        // 0x0660(0x00A0)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UFitingSlotItem_BP_C*>           SlotItemArray;                                     // 0x0700(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	TArray<int32>                                 AttachNameArray;                                   // 0x0710(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	TMap<EWeaponAttachmentSocketType, int32>      Slot2Index;                                        // 0x0720(0x0050)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	UMulticastDelegateProperty_                   ShowToolTip;                                       // 0x0770(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class FString                                 InputKeyActionName;                                // 0x0780(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	class UTextureRenderTarget2D*                 RenderTargetTexture;                               // 0x0790(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AItemStudio*                            ItemStudio;                                        // 0x0798(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               WeaponCaptureMaterial;                             // 0x07A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	UMulticastDelegateProperty_                   UpdateAvatar;                                      // 0x07A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_PistolInfoItem_BP(int32 EntryPoint);
	void BndEvt__GripSlot_K2Node_ComponentBoundEvent_422_OnLeaveSlot__DelegateSignature();
	void BndEvt__StockSlot_K2Node_ComponentBoundEvent_409_OnLeaveSlot__DelegateSignature();
	void UpdateAvatar_Event();
	void ReceiveShow();
	void ReceiveHide();
	void OnDragLeave(const struct FPointerEvent& PointerEvent, class UDragDropOperation* Operation);
	void OnDragEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& PointerEvent, class UDragDropOperation* Operation);
	void OnRightClicked(const struct FVector2D& TempScreenPos);
	void OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void BndEvt__FitingSlotItem_BP_C_1_K2Node_ComponentBoundEvent_34_OnLeaveSlot__DelegateSignature();
	void BndEvt__FitingSlotItem_BP_C_0_K2Node_ComponentBoundEvent_20_OnLeaveSlot__DelegateSignature();
	void BndEvt__FitingSlotItem_BP_K2Node_ComponentBoundEvent_7_OnLeaveSlot__DelegateSignature();
	void ShowToolTipAttachment(const struct FSlateBrush& Brush, const struct FBattleItemData& BattleItemData, uint8 IsShow);
	void OnMouseLeave(const struct FPointerEvent& MouseEvent);
	void OnDragCancelled(const struct FPointerEvent& PointerEvent, class UDragDropOperation* Operation);
	void FittingItemBeDragCancel();
	void FittingItemBeDragBegin(const struct FBattleItemData& ItemData, EBackPackDragOrigin DragOrigin);
	void ReceivedInitWidget();
	struct FEventReply OnTouchStarted(const struct FGeometry& MyGeometry, struct FPointerEvent& InTouchEvent);
	struct FEventReply OnTouchEnded(const struct FGeometry& MyGeometry, struct FPointerEvent& InTouchEvent);
	void UpdateWeaponAppearanceInfo(const struct FBP_STRUCT_Item_type& Record, const struct FBattleItemData& ItemData);
	void HighLightBG(uint8 IsHighLight);
	void UpdateBullet();
	void UpdateSlotVisibility();
	void UpdateWeaponAttachment();
	void OnDragDetected(const struct FGeometry& MyGeometry, struct FPointerEvent& PointerEvent, class UDragDropOperation** Operation);
	void HighLightAttachSlot(const struct FItemDefineID& DefineID);
	void ResertHighLightAttachSlot();
	void UpdateUsingSlot(ESurviveWeaponPropSlot Slot_0);
	void BindWeaponChangeEvent();
	struct FEventReply OnMouseButtonDown(const struct FGeometry& MyGeometry, struct FPointerEvent& MouseEvent);
	struct FEventReply OnMouseButtonUp(const struct FGeometry& MyGeometry, struct FPointerEvent& MouseEvent);
	void IsAttachSlotMouseOver(uint8* IsMouseOver);
	void UpdateRenderTexture();
	void OnSpawnActorInSceneCaptureWorld(class AActor* SpawnedActor);
	void IsValidWeapon(uint8* IsValid);
	void HighLightBG_Dark(uint8 IsHighLight);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PistolInfoItem_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PistolInfoItem_BP_C")
	}
	static class UPistolInfoItem_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPistolInfoItem_BP_C>();
	}
};

}

