#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PresetColorComboBoxWidget

#include "Basic.hpp"

#include "QualityComboBox_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PresetColorComboBoxWidget.PresetColorComboBoxWidget_C
// 0x0008 (0x0278 - 0x0270)
class UPresetColorComboBoxWidget_C final : public UQualityComboBox_C
{
public:
	class UPresetColorWidget_C*                   ColorRef;                                          // 0x0270(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	class UWidget* On_ComboBox_GenerateWidget_0(const class FString& Item);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PresetColorComboBoxWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PresetColorComboBoxWidget_C")
	}
	static class UPresetColorComboBoxWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPresetColorComboBoxWidget_C>();
	}
};

}

