#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SK_WEP_98k_AnimBP

#include "Basic.hpp"

#include "ShadowTrackerExtra_structs.hpp"
#include "Gameplay_structs.hpp"


namespace SDK::Params
{

// Function SK_WEP_98k_AnimBP.SK_WEP_98k_AnimBP_C.ExecuteUbergraph_SK_WEP_98k_AnimBP
// 0x0190 (0x0190 - 0x0000)
struct SK_WEP_98k_AnimBP_C_ExecuteUbergraph_SK_WEP_98k_AnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(EWeaponReloadAnimExec AnimExec)> K2Node_CreateDelegate_OutputDelegate;            // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         ___bool_Has_Been_Initd_Variable : 1;               // 0x0018(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         ___bool_IsClosed_Variable : 1;                     // 0x0019(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_1A[0x6];                                       // 0x001A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(EFreshWeaponStateType CurState)> K2Node_CreateDelegate_OutputDelegate2;           // 0x0020(0x0010)(ZeroConstructor, NoDestructor)
	float                                         K2Node_Event_DeltaTimeX;                           // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActor_ReturnValue;               // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASTExtraShootWeapon*                    K2Node_DynamicCast_AsSTExtra_Shoot_Weapon;         // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess : 1;                   // 0x0048(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	EFreshWeaponStateType                         K2Node_CustomEvent_CurState;                       // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4A[0x6];                                       // 0x004A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_IsValid_ReturnValue : 1;                  // 0x0058(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASTExtraBaseCharacter*                  K2Node_DynamicCast_AsSTExtra_Base_Character;       // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess2 : 1;                  // 0x0068(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_EqualEqual_ByteByte_ReturnValue : 1;      // 0x0069(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_6A[0x6];                                       // 0x006A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPlayerAnimList                        CallFunc_GetPlayerAnimation_ReturnValue;           // 0x0070(0x00F0)()
	TDelegate<void(EWeaponReloadAnimExec AnimExec)> K2Node_CreateDelegate_OutputDelegate3;           // 0x0160(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         ___bool_Has_Been_Initd_Variable2 : 1;              // 0x0170(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_EqualEqual_ByteByte_ReturnValue2 : 1;     // 0x0171(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         ___bool_IsClosed_Variable2 : 1;                    // 0x0172(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_173[0x1];                                      // 0x0173(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_CustomEvent_AvailableAmmoCount;             // 0x0174(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(int32 AvailableAmmoCount)>     K2Node_CreateDelegate_OutputDelegate4;             // 0x0178(0x0010)(ZeroConstructor, NoDestructor)
	EWeaponReloadAnimExec                         K2Node_CustomEvent_AnimExec2;                      // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EWeaponReloadAnimExec                         K2Node_CustomEvent_AnimExec;                       // 0x0189(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SK_WEP_98k_AnimBP.SK_WEP_98k_AnimBP_C.StartReloadMagazineDelegate_이벤트_0
// 0x0001 (0x0001 - 0x0000)
struct SK_WEP_98k_AnimBP_C_StartReloadMagazineDelegate_이벤트_0 final
{
public:
	EWeaponReloadAnimExec                         AnimExec;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SK_WEP_98k_AnimBP.SK_WEP_98k_AnimBP_C.StartReloadByOneDelegate_이벤트_0
// 0x0001 (0x0001 - 0x0000)
struct SK_WEP_98k_AnimBP_C_StartReloadByOneDelegate_이벤트_0 final
{
public:
	EWeaponReloadAnimExec                         AnimExec;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SK_WEP_98k_AnimBP.SK_WEP_98k_AnimBP_C.Custom Event_0
// 0x0004 (0x0004 - 0x0000)
struct SK_WEP_98k_AnimBP_C_Custom_Event_0 final
{
public:
	int32                                         AvailableAmmoCount;                                // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SK_WEP_98k_AnimBP.SK_WEP_98k_AnimBP_C.OnWeaponChangeState
// 0x0001 (0x0001 - 0x0000)
struct SK_WEP_98k_AnimBP_C_OnWeaponChangeState final
{
public:
	EFreshWeaponStateType                         CurState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SK_WEP_98k_AnimBP.SK_WEP_98k_AnimBP_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct SK_WEP_98k_AnimBP_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SK_WEP_98k_AnimBP.SK_WEP_98k_AnimBP_C.PlayBoltAnim
// 0x0004 (0x0004 - 0x0000)
struct SK_WEP_98k_AnimBP_C_PlayBoltAnim final
{
public:
	float                                         CallFunc_Montage_Play_ReturnValue;                 // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SK_WEP_98k_AnimBP.SK_WEP_98k_AnimBP_C.HandleWeaponStateChanged
// 0x0028 (0x0028 - 0x0000)
struct SK_WEP_98k_AnimBP_C_HandleWeaponStateChanged final
{
public:
	EFreshWeaponStateType                         NewParam;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActor_ReturnValue;               // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_SwitchEnum_CmpSuccess : 1;                  // 0x0010(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASTExtraShootWeapon*                    K2Node_DynamicCast_AsSTExtra_Shoot_Weapon;         // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess : 1;                   // 0x0020(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_NotEqual_ByteByte_ReturnValue : 1;        // 0x0021(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function SK_WEP_98k_AnimBP.SK_WEP_98k_AnimBP_C.StartReloadByOne
// 0x0020 (0x0020 - 0x0000)
struct SK_WEP_98k_AnimBP_C_StartReloadByOne final
{
public:
	class AActor*                                 CallFunc_GetOwningActor_ReturnValue;               // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASTExtraShootWeapon*                    K2Node_DynamicCast_AsSTExtra_Shoot_Weapon;         // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess : 1;                   // 0x0010(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetReloadAnimRate_ReturnValue;            // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Montage_Play_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SK_WEP_98k_AnimBP.SK_WEP_98k_AnimBP_C.UpdateReloadType
// 0x0120 (0x0120 - 0x0000)
struct SK_WEP_98k_AnimBP_C_UpdateReloadType final
{
public:
	class AActor*                                 CallFunc_GetOwningActor_ReturnValue;               // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASTExtraShootWeapon*                    K2Node_DynamicCast_AsSTExtra_Shoot_Weapon;         // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess : 1;                   // 0x0010(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASTExtraBaseCharacter*                  K2Node_DynamicCast_AsSTExtra_Base_Character;       // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess2 : 1;                  // 0x0028(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimParamList                         CallFunc_GetPlayerAnimParam_ReturnValue;           // 0x002C(0x00F0)(NoDestructor)
	uint8                                         CallFunc_EqualEqual_ByteByte_ReturnValue : 1;      // 0x011C(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_EqualEqual_ByteByte_ReturnValue2 : 1;     // 0x011D(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

// Function SK_WEP_98k_AnimBP.SK_WEP_98k_AnimBP_C.StartReloadByMagazine
// 0x0020 (0x0020 - 0x0000)
struct SK_WEP_98k_AnimBP_C_StartReloadByMagazine final
{
public:
	class AActor*                                 CallFunc_GetOwningActor_ReturnValue;               // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASTExtraShootWeapon*                    K2Node_DynamicCast_AsSTExtra_Shoot_Weapon;         // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess : 1;                   // 0x0010(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetReloadAnimRate_ReturnValue;            // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Montage_Play_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SK_WEP_98k_AnimBP.SK_WEP_98k_AnimBP_C.GetReloadingRemainAmmo
// 0x0038 (0x0038 - 0x0000)
struct SK_WEP_98k_AnimBP_C_GetReloadingRemainAmmo final
{
public:
	int32                                         RemainAmmo;                                        // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActor_ReturnValue;               // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASTExtraShootWeapon*                    K2Node_DynamicCast_AsSTExtra_Shoot_Weapon;         // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess : 1;                   // 0x0018(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASTExtraBaseCharacter*                  K2Node_DynamicCast_AsSTExtra_Base_Character;       // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_DynamicCast_bSuccess2 : 1;                  // 0x0030(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetReloadingRemainAmmo_ReturnValue;       // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function SK_WEP_98k_AnimBP.SK_WEP_98k_AnimBP_C.CheckBreakReloadLoop
// 0x0028 (0x0028 - 0x0000)
struct alignas(0x08) SK_WEP_98k_AnimBP_C_CheckBreakReloadLoop final
{
public:
	int32                                         CallFunc_GetReloadingRemainAmmo_RemainAmmo;        // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Montage_GetCurrentSection_ReturnValue;    // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_LessEqual_IntInt_ReturnValue : 1;         // 0x0010(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_Montage_IsPlaying_ReturnValue : 1;        // 0x0011(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Montage_GetCurrentSection_ReturnValue2;   // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_NotEqual_NameName_ReturnValue : 1;        // 0x0020(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
	uint8                                         CallFunc_BooleanAND_ReturnValue : 1;               // 0x0021(0x0001)(BitIndex: 0xFF, PropSize: 0x0001 (ZeroConstructor, IsPlainOldData, NoDestructor))
};

}

