#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SR_BP

#include "Basic.hpp"

#include "ShadowTrackerExtra_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SR_BP.SR_BP_C
// 0x0000 (0x0040 - 0x0040)
class USR_BP_C final : public URespawnItemConfig
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SR_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SR_BP_C")
	}
	static class USR_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USR_BP_C>();
	}
};

}

