#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VH_Motorcycle_WheelHubBack_LPC

#include "Basic.hpp"

#include "ShadowTrackerExtra_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass VH_Motorcycle_WheelHubBack_LPC.VH_Motorcycle_WheelHubBack_LPC_C
// 0x0000 (0x0128 - 0x0128)
class UVH_Motorcycle_WheelHubBack_LPC_C final : public USTExtraVehicleWheel
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("VH_Motorcycle_WheelHubBack_LPC_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VH_Motorcycle_WheelHubBack_LPC_C")
	}
	static class UVH_Motorcycle_WheelHubBack_LPC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVH_Motorcycle_WheelHubBack_LPC_C>();
	}
};

}

